// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: tube.proto

package tube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCProtocol int32

const (
	RPCProtocol_JSONRPC RPCProtocol = 0
)

// Enum value maps for RPCProtocol.
var (
	RPCProtocol_name = map[int32]string{
		0: "JSONRPC",
	}
	RPCProtocol_value = map[string]int32{
		"JSONRPC": 0,
	}
)

func (x RPCProtocol) Enum() *RPCProtocol {
	p := new(RPCProtocol)
	*p = x
	return p
}

func (x RPCProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPCProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_tube_proto_enumTypes[0].Descriptor()
}

func (RPCProtocol) Type() protoreflect.EnumType {
	return &file_tube_proto_enumTypes[0]
}

func (x RPCProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPCProtocol.Descriptor instead.
func (RPCProtocol) EnumDescriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{0}
}

type MethodLocation int32

const (
	MethodLocation_LOCAL  MethodLocation = 0
	MethodLocation_REMOTE MethodLocation = 1
)

// Enum value maps for MethodLocation.
var (
	MethodLocation_name = map[int32]string{
		0: "LOCAL",
		1: "REMOTE",
	}
	MethodLocation_value = map[string]int32{
		"LOCAL":  0,
		"REMOTE": 1,
	}
)

func (x MethodLocation) Enum() *MethodLocation {
	p := new(MethodLocation)
	*p = x
	return p
}

func (x MethodLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MethodLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_tube_proto_enumTypes[1].Descriptor()
}

func (MethodLocation) Type() protoreflect.EnumType {
	return &file_tube_proto_enumTypes[1]
}

func (x MethodLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MethodLocation.Descriptor instead.
func (MethodLocation) EnumDescriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{0}
}

type ListMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMethodsRequest) Reset() {
	*x = ListMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsRequest) ProtoMessage() {}

func (x *ListMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{1}
}

type ListMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *ListMethodsResponse) Reset() {
	*x = ListMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsResponse) ProtoMessage() {}

func (x *ListMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListMethodsResponse) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{2}
}

func (x *ListMethodsResponse) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type SubscribeMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeMethodsRequest) Reset() {
	*x = SubscribeMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMethodsRequest) ProtoMessage() {}

func (x *SubscribeMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMethodsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{3}
}

type MethodUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *MethodUpdate) Reset() {
	*x = MethodUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodUpdate) ProtoMessage() {}

func (x *MethodUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodUpdate.ProtoReflect.Descriptor instead.
func (*MethodUpdate) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{4}
}

func (x *MethodUpdate) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type MetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{5}
}

type MetaResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries      []*RPCEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	PingInterval int32       `protobuf:"varint,3,opt,name=ping_interval,json=pingInterval,proto3" json:"ping_interval,omitempty"`
}

func (x *MetaResult) Reset() {
	*x = MetaResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResult) ProtoMessage() {}

func (x *MetaResult) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResult.ProtoReflect.Descriptor instead.
func (*MetaResult) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{6}
}

func (x *MetaResult) GetEntries() []*RPCEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *MetaResult) GetPingInterval() int32 {
	if x != nil {
		return x.PingInterval
	}
	return 0
}

type RPCEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol RPCProtocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=RPCProtocol" json:"protocol,omitempty"`
	Name     string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Help     string      `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
}

func (x *RPCEntry) Reset() {
	*x = RPCEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCEntry) ProtoMessage() {}

func (x *RPCEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCEntry.ProtoReflect.Descriptor instead.
func (*RPCEntry) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{7}
}

func (x *RPCEntry) GetProtocol() RPCProtocol {
	if x != nil {
		return x.Protocol
	}
	return RPCProtocol_JSONRPC
}

func (x *RPCEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RPCEntry) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

type JSONRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//string id = 1;  // empty id means notify
	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params string `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"` // JSON encoded
}

func (x *JSONRPCRequest) Reset() {
	*x = JSONRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCRequest) ProtoMessage() {}

func (x *JSONRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCRequest.ProtoReflect.Descriptor instead.
func (*JSONRPCRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{8}
}

func (x *JSONRPCRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JSONRPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *JSONRPCRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type JSONRPCResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//string id = 1;
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Result:
	//	*JSONRPCResult_Ok
	//	*JSONRPCResult_Error
	Result isJSONRPCResult_Result `protobuf_oneof:"result"`
}

func (x *JSONRPCResult) Reset() {
	*x = JSONRPCResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCResult) ProtoMessage() {}

func (x *JSONRPCResult) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCResult.ProtoReflect.Descriptor instead.
func (*JSONRPCResult) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{9}
}

func (x *JSONRPCResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *JSONRPCResult) GetResult() isJSONRPCResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *JSONRPCResult) GetOk() string {
	if x, ok := x.GetResult().(*JSONRPCResult_Ok); ok {
		return x.Ok
	}
	return ""
}

func (x *JSONRPCResult) GetError() string {
	if x, ok := x.GetResult().(*JSONRPCResult_Error); ok {
		return x.Error
	}
	return ""
}

type isJSONRPCResult_Result interface {
	isJSONRPCResult_Result()
}

type JSONRPCResult_Ok struct {
	Ok string `protobuf:"bytes,10,opt,name=ok,proto3,oneof"` // JSON encoded
}

type JSONRPCResult_Error struct {
	Error string `protobuf:"bytes,11,opt,name=error,proto3,oneof"` // JSON encoded
}

func (*JSONRPCResult_Ok) isJSONRPCResult_Result() {}

func (*JSONRPCResult_Error) isJSONRPCResult_Result() {}

type RegisterMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods     []string       `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	Localcation MethodLocation `protobuf:"varint,2,opt,name=localcation,proto3,enum=MethodLocation" json:"localcation,omitempty"`
}

func (x *RegisterMethodsRequest) Reset() {
	*x = RegisterMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMethodsRequest) ProtoMessage() {}

func (x *RegisterMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMethodsRequest.ProtoReflect.Descriptor instead.
func (*RegisterMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterMethodsRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *RegisterMethodsRequest) GetLocalcation() MethodLocation {
	if x != nil {
		return x.Localcation
	}
	return MethodLocation_LOCAL
}

type UnRegisterMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *UnRegisterMethodsRequest) Reset() {
	*x = UnRegisterMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterMethodsRequest) ProtoMessage() {}

func (x *UnRegisterMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterMethodsRequest.ProtoReflect.Descriptor instead.
func (*UnRegisterMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{11}
}

func (x *UnRegisterMethodsRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type RegisterMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *RegisterMethodsResponse) Reset() {
	*x = RegisterMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMethodsResponse) ProtoMessage() {}

func (x *RegisterMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMethodsResponse.ProtoReflect.Descriptor instead.
func (*RegisterMethodsResponse) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterMethodsResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UnRegisterMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *UnRegisterMethodsResponse) Reset() {
	*x = UnRegisterMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterMethodsResponse) ProtoMessage() {}

func (x *UnRegisterMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterMethodsResponse.ProtoReflect.Descriptor instead.
func (*UnRegisterMethodsResponse) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{13}
}

func (x *UnRegisterMethodsResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PING struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PING) Reset() {
	*x = PING{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PING) ProtoMessage() {}

func (x *PING) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PING.ProtoReflect.Descriptor instead.
func (*PING) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{14}
}

func (x *PING) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PONG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PONG) Reset() {
	*x = PONG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PONG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PONG) ProtoMessage() {}

func (x *PONG) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PONG.ProtoReflect.Descriptor instead.
func (*PONG) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{15}
}

func (x *PONG) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type JSONRPCDownPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JSONRPCDownPacket_RegisterMethods
	//	*JSONRPCDownPacket_UnregisterMethods
	//	*JSONRPCDownPacket_Ping
	//	*JSONRPCDownPacket_Pong
	//	*JSONRPCDownPacket_Request
	Payload isJSONRPCDownPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JSONRPCDownPacket) Reset() {
	*x = JSONRPCDownPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCDownPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCDownPacket) ProtoMessage() {}

func (x *JSONRPCDownPacket) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCDownPacket.ProtoReflect.Descriptor instead.
func (*JSONRPCDownPacket) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{16}
}

func (m *JSONRPCDownPacket) GetPayload() isJSONRPCDownPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JSONRPCDownPacket) GetRegisterMethods() *RegisterMethodsResponse {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_RegisterMethods); ok {
		return x.RegisterMethods
	}
	return nil
}

func (x *JSONRPCDownPacket) GetUnregisterMethods() *UnRegisterMethodsResponse {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_UnregisterMethods); ok {
		return x.UnregisterMethods
	}
	return nil
}

func (x *JSONRPCDownPacket) GetPing() *PING {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *JSONRPCDownPacket) GetPong() *PONG {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *JSONRPCDownPacket) GetRequest() *JSONRPCRequest {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_Request); ok {
		return x.Request
	}
	return nil
}

type isJSONRPCDownPacket_Payload interface {
	isJSONRPCDownPacket_Payload()
}

type JSONRPCDownPacket_RegisterMethods struct {
	//MetaRequest meta_request = 1;
	RegisterMethods *RegisterMethodsResponse `protobuf:"bytes,1,opt,name=register_methods,json=registerMethods,proto3,oneof"`
}

type JSONRPCDownPacket_UnregisterMethods struct {
	UnregisterMethods *UnRegisterMethodsResponse `protobuf:"bytes,2,opt,name=unregister_methods,json=unregisterMethods,proto3,oneof"`
}

type JSONRPCDownPacket_Ping struct {
	Ping *PING `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type JSONRPCDownPacket_Pong struct {
	Pong *PONG `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

type JSONRPCDownPacket_Request struct {
	Request *JSONRPCRequest `protobuf:"bytes,10,opt,name=request,proto3,oneof"`
}

func (*JSONRPCDownPacket_RegisterMethods) isJSONRPCDownPacket_Payload() {}

func (*JSONRPCDownPacket_UnregisterMethods) isJSONRPCDownPacket_Payload() {}

func (*JSONRPCDownPacket_Ping) isJSONRPCDownPacket_Payload() {}

func (*JSONRPCDownPacket_Pong) isJSONRPCDownPacket_Payload() {}

func (*JSONRPCDownPacket_Request) isJSONRPCDownPacket_Payload() {}

type JSONRPCUpPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JSONRPCUpPacket_RegisterMethods
	//	*JSONRPCUpPacket_UnregisterMethods
	//	*JSONRPCUpPacket_Ping
	//	*JSONRPCUpPacket_Pong
	//	*JSONRPCUpPacket_Result
	Payload isJSONRPCUpPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JSONRPCUpPacket) Reset() {
	*x = JSONRPCUpPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCUpPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCUpPacket) ProtoMessage() {}

func (x *JSONRPCUpPacket) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCUpPacket.ProtoReflect.Descriptor instead.
func (*JSONRPCUpPacket) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{17}
}

func (m *JSONRPCUpPacket) GetPayload() isJSONRPCUpPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JSONRPCUpPacket) GetRegisterMethods() *RegisterMethodsRequest {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_RegisterMethods); ok {
		return x.RegisterMethods
	}
	return nil
}

func (x *JSONRPCUpPacket) GetUnregisterMethods() *UnRegisterMethodsRequest {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_UnregisterMethods); ok {
		return x.UnregisterMethods
	}
	return nil
}

func (x *JSONRPCUpPacket) GetPing() *PING {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *JSONRPCUpPacket) GetPong() *PONG {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *JSONRPCUpPacket) GetResult() *JSONRPCResult {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_Result); ok {
		return x.Result
	}
	return nil
}

type isJSONRPCUpPacket_Payload interface {
	isJSONRPCUpPacket_Payload()
}

type JSONRPCUpPacket_RegisterMethods struct {
	//MetaResult meta_result = 1;
	RegisterMethods *RegisterMethodsRequest `protobuf:"bytes,1,opt,name=register_methods,json=registerMethods,proto3,oneof"`
}

type JSONRPCUpPacket_UnregisterMethods struct {
	UnregisterMethods *UnRegisterMethodsRequest `protobuf:"bytes,2,opt,name=unregister_methods,json=unregisterMethods,proto3,oneof"`
}

type JSONRPCUpPacket_Ping struct {
	Ping *PING `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type JSONRPCUpPacket_Pong struct {
	Pong *PONG `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

type JSONRPCUpPacket_Result struct {
	Result *JSONRPCResult `protobuf:"bytes,10,opt,name=result,proto3,oneof"`
}

func (*JSONRPCUpPacket_RegisterMethods) isJSONRPCUpPacket_Payload() {}

func (*JSONRPCUpPacket_UnregisterMethods) isJSONRPCUpPacket_Payload() {}

func (*JSONRPCUpPacket_Ping) isJSONRPCUpPacket_Payload() {}

func (*JSONRPCUpPacket_Pong) isJSONRPCUpPacket_Payload() {}

func (*JSONRPCUpPacket_Result) isJSONRPCUpPacket_Payload() {}

var File_tube_proto protoreflect.FileDescriptor

var file_tube_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x75, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x19, 0x0a, 0x17,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x56, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x23,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x69, 0x6e, 0x67,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x5c, 0x0a, 0x08, 0x52, 0x50, 0x43, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x52, 0x50, 0x43, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x22, 0x50, 0x0a, 0x0e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50,
	0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x53, 0x0a, 0x0d, 0x4a, 0x53, 0x4f, 0x4e,
	0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x65, 0x0a,
	0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x73, 0x12, 0x31, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x18, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x2d, 0x0a, 0x17, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2f, 0x0a, 0x19, 0x55, 0x6e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x49,
	0x4e, 0x47, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x22, 0x99, 0x02, 0x0a, 0x11, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x44, 0x6f,
	0x77, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x45, 0x0a, 0x10, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12,
	0x4b, 0x0a, 0x12, 0x75, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x55, 0x6e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x75, 0x6e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x49, 0x4e,
	0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x6f, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x4f, 0x4e, 0x47, 0x48, 0x00,
	0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50,
	0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x92,
	0x02, 0x0a, 0x0f, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x55, 0x70, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x44, 0x0a, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x4a, 0x0a, 0x12, 0x75, 0x6e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x11, 0x75, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x49, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e,
	0x67, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x50, 0x4f, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x28,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2a, 0x1a, 0x0a, 0x0b, 0x52, 0x50, 0x43, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x12, 0x0b, 0x0a, 0x07, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x10, 0x00, 0x2a,
	0x27, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x10, 0x01, 0x32, 0xa4, 0x01, 0x0a, 0x0b, 0x4a, 0x53, 0x4f,
	0x4e, 0x52, 0x50, 0x43, 0x54, 0x75, 0x62, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0f, 0x2e, 0x4a, 0x53, 0x4f,
	0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x4a, 0x53,
	0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x55,
	0x70, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x12, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50,
	0x43, 0x44, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x0b, 0x5a, 0x09, 0x69, 0x6e, 0x74, 0x66, 0x2f, 0x74, 0x75, 0x62, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tube_proto_rawDescOnce sync.Once
	file_tube_proto_rawDescData = file_tube_proto_rawDesc
)

func file_tube_proto_rawDescGZIP() []byte {
	file_tube_proto_rawDescOnce.Do(func() {
		file_tube_proto_rawDescData = protoimpl.X.CompressGZIP(file_tube_proto_rawDescData)
	})
	return file_tube_proto_rawDescData
}

var file_tube_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tube_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_tube_proto_goTypes = []interface{}{
	(RPCProtocol)(0),                  // 0: RPCProtocol
	(MethodLocation)(0),               // 1: MethodLocation
	(*Empty)(nil),                     // 2: Empty
	(*ListMethodsRequest)(nil),        // 3: ListMethodsRequest
	(*ListMethodsResponse)(nil),       // 4: ListMethodsResponse
	(*SubscribeMethodsRequest)(nil),   // 5: SubscribeMethodsRequest
	(*MethodUpdate)(nil),              // 6: MethodUpdate
	(*MetaRequest)(nil),               // 7: MetaRequest
	(*MetaResult)(nil),                // 8: MetaResult
	(*RPCEntry)(nil),                  // 9: RPCEntry
	(*JSONRPCRequest)(nil),            // 10: JSONRPCRequest
	(*JSONRPCResult)(nil),             // 11: JSONRPCResult
	(*RegisterMethodsRequest)(nil),    // 12: RegisterMethodsRequest
	(*UnRegisterMethodsRequest)(nil),  // 13: UnRegisterMethodsRequest
	(*RegisterMethodsResponse)(nil),   // 14: RegisterMethodsResponse
	(*UnRegisterMethodsResponse)(nil), // 15: UnRegisterMethodsResponse
	(*PING)(nil),                      // 16: PING
	(*PONG)(nil),                      // 17: PONG
	(*JSONRPCDownPacket)(nil),         // 18: JSONRPCDownPacket
	(*JSONRPCUpPacket)(nil),           // 19: JSONRPCUpPacket
}
var file_tube_proto_depIdxs = []int32{
	9,  // 0: MetaResult.entries:type_name -> RPCEntry
	0,  // 1: RPCEntry.protocol:type_name -> RPCProtocol
	1,  // 2: RegisterMethodsRequest.localcation:type_name -> MethodLocation
	14, // 3: JSONRPCDownPacket.register_methods:type_name -> RegisterMethodsResponse
	15, // 4: JSONRPCDownPacket.unregister_methods:type_name -> UnRegisterMethodsResponse
	16, // 5: JSONRPCDownPacket.ping:type_name -> PING
	17, // 6: JSONRPCDownPacket.pong:type_name -> PONG
	10, // 7: JSONRPCDownPacket.request:type_name -> JSONRPCRequest
	12, // 8: JSONRPCUpPacket.register_methods:type_name -> RegisterMethodsRequest
	13, // 9: JSONRPCUpPacket.unregister_methods:type_name -> UnRegisterMethodsRequest
	16, // 10: JSONRPCUpPacket.ping:type_name -> PING
	17, // 11: JSONRPCUpPacket.pong:type_name -> PONG
	11, // 12: JSONRPCUpPacket.result:type_name -> JSONRPCResult
	3,  // 13: JSONRPCTube.ListMethods:input_type -> ListMethodsRequest
	10, // 14: JSONRPCTube.Call:input_type -> JSONRPCRequest
	19, // 15: JSONRPCTube.Handle:input_type -> JSONRPCUpPacket
	4,  // 16: JSONRPCTube.ListMethods:output_type -> ListMethodsResponse
	11, // 17: JSONRPCTube.Call:output_type -> JSONRPCResult
	18, // 18: JSONRPCTube.Handle:output_type -> JSONRPCDownPacket
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tube_proto_init() }
func file_tube_proto_init() {
	if File_tube_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tube_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PING); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PONG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCDownPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCUpPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tube_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*JSONRPCResult_Ok)(nil),
		(*JSONRPCResult_Error)(nil),
	}
	file_tube_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*JSONRPCDownPacket_RegisterMethods)(nil),
		(*JSONRPCDownPacket_UnregisterMethods)(nil),
		(*JSONRPCDownPacket_Ping)(nil),
		(*JSONRPCDownPacket_Pong)(nil),
		(*JSONRPCDownPacket_Request)(nil),
	}
	file_tube_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*JSONRPCUpPacket_RegisterMethods)(nil),
		(*JSONRPCUpPacket_UnregisterMethods)(nil),
		(*JSONRPCUpPacket_Ping)(nil),
		(*JSONRPCUpPacket_Pong)(nil),
		(*JSONRPCUpPacket_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tube_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tube_proto_goTypes,
		DependencyIndexes: file_tube_proto_depIdxs,
		EnumInfos:         file_tube_proto_enumTypes,
		MessageInfos:      file_tube_proto_msgTypes,
	}.Build()
	File_tube_proto = out.File
	file_tube_proto_rawDesc = nil
	file_tube_proto_goTypes = nil
	file_tube_proto_depIdxs = nil
}
