// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: tube.proto

package tube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCProtocol int32

const (
	RPCProtocol_JSONRPC RPCProtocol = 0
)

// Enum value maps for RPCProtocol.
var (
	RPCProtocol_name = map[int32]string{
		0: "JSONRPC",
	}
	RPCProtocol_value = map[string]int32{
		"JSONRPC": 0,
	}
)

func (x RPCProtocol) Enum() *RPCProtocol {
	p := new(RPCProtocol)
	*p = x
	return p
}

func (x RPCProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPCProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_tube_proto_enumTypes[0].Descriptor()
}

func (RPCProtocol) Type() protoreflect.EnumType {
	return &file_tube_proto_enumTypes[0]
}

func (x RPCProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPCProtocol.Descriptor instead.
func (RPCProtocol) EnumDescriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{0}
}

type MethodsDecl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entrypoint string   `protobuf:"bytes,1,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Methods    []string `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *MethodsDecl) Reset() {
	*x = MethodsDecl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodsDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodsDecl) ProtoMessage() {}

func (x *MethodsDecl) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodsDecl.ProtoReflect.Descriptor instead.
func (*MethodsDecl) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{1}
}

func (x *MethodsDecl) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *MethodsDecl) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type UpdateMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *UpdateMethodsResponse) Reset() {
	*x = UpdateMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMethodsResponse) ProtoMessage() {}

func (x *UpdateMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMethodsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMethodsResponse) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMethodsResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type GetMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMethodsRequest) Reset() {
	*x = GetMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMethodsRequest) ProtoMessage() {}

func (x *GetMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMethodsRequest.ProtoReflect.Descriptor instead.
func (*GetMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{3}
}

type GetMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *GetMethodsResponse) Reset() {
	*x = GetMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMethodsResponse) ProtoMessage() {}

func (x *GetMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMethodsResponse.ProtoReflect.Descriptor instead.
func (*GetMethodsResponse) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{4}
}

func (x *GetMethodsResponse) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type SubscribeMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeMethodsRequest) Reset() {
	*x = SubscribeMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMethodsRequest) ProtoMessage() {}

func (x *SubscribeMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMethodsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{5}
}

type MethodUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *MethodUpdate) Reset() {
	*x = MethodUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodUpdate) ProtoMessage() {}

func (x *MethodUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodUpdate.ProtoReflect.Descriptor instead.
func (*MethodUpdate) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{6}
}

func (x *MethodUpdate) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type MetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{7}
}

type MetaResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries      []*RPCEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	PingInterval int32       `protobuf:"varint,3,opt,name=ping_interval,json=pingInterval,proto3" json:"ping_interval,omitempty"`
}

func (x *MetaResult) Reset() {
	*x = MetaResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResult) ProtoMessage() {}

func (x *MetaResult) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResult.ProtoReflect.Descriptor instead.
func (*MetaResult) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{8}
}

func (x *MetaResult) GetEntries() []*RPCEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *MetaResult) GetPingInterval() int32 {
	if x != nil {
		return x.PingInterval
	}
	return 0
}

type RPCEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol RPCProtocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=RPCProtocol" json:"protocol,omitempty"`
	Name     string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Help     string      `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
}

func (x *RPCEntry) Reset() {
	*x = RPCEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCEntry) ProtoMessage() {}

func (x *RPCEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCEntry.ProtoReflect.Descriptor instead.
func (*RPCEntry) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{9}
}

func (x *RPCEntry) GetProtocol() RPCProtocol {
	if x != nil {
		return x.Protocol
	}
	return RPCProtocol_JSONRPC
}

func (x *RPCEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RPCEntry) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

type JSONRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//string id = 1;  // empty id means notify
	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params string `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"` // JSON encoded
}

func (x *JSONRPCRequest) Reset() {
	*x = JSONRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCRequest) ProtoMessage() {}

func (x *JSONRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCRequest.ProtoReflect.Descriptor instead.
func (*JSONRPCRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{10}
}

func (x *JSONRPCRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JSONRPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *JSONRPCRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type JSONRPCResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//string id = 1;
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Result:
	//	*JSONRPCResult_Ok
	//	*JSONRPCResult_Error
	Result isJSONRPCResult_Result `protobuf_oneof:"result"`
}

func (x *JSONRPCResult) Reset() {
	*x = JSONRPCResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCResult) ProtoMessage() {}

func (x *JSONRPCResult) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCResult.ProtoReflect.Descriptor instead.
func (*JSONRPCResult) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{11}
}

func (x *JSONRPCResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *JSONRPCResult) GetResult() isJSONRPCResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *JSONRPCResult) GetOk() string {
	if x, ok := x.GetResult().(*JSONRPCResult_Ok); ok {
		return x.Ok
	}
	return ""
}

func (x *JSONRPCResult) GetError() string {
	if x, ok := x.GetResult().(*JSONRPCResult_Error); ok {
		return x.Error
	}
	return ""
}

type isJSONRPCResult_Result interface {
	isJSONRPCResult_Result()
}

type JSONRPCResult_Ok struct {
	Ok string `protobuf:"bytes,10,opt,name=ok,proto3,oneof"` // JSON encoded
}

type JSONRPCResult_Error struct {
	Error string `protobuf:"bytes,11,opt,name=error,proto3,oneof"` // JSON encoded
}

func (*JSONRPCResult_Ok) isJSONRPCResult_Result() {}

func (*JSONRPCResult_Error) isJSONRPCResult_Result() {}

type JSONRPCRequestPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JSONRPCRequestPacket_MetaRequest
	//	*JSONRPCRequestPacket_Request
	Payload isJSONRPCRequestPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JSONRPCRequestPacket) Reset() {
	*x = JSONRPCRequestPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCRequestPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCRequestPacket) ProtoMessage() {}

func (x *JSONRPCRequestPacket) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCRequestPacket.ProtoReflect.Descriptor instead.
func (*JSONRPCRequestPacket) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{12}
}

func (m *JSONRPCRequestPacket) GetPayload() isJSONRPCRequestPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JSONRPCRequestPacket) GetMetaRequest() *MetaRequest {
	if x, ok := x.GetPayload().(*JSONRPCRequestPacket_MetaRequest); ok {
		return x.MetaRequest
	}
	return nil
}

func (x *JSONRPCRequestPacket) GetRequest() *JSONRPCRequest {
	if x, ok := x.GetPayload().(*JSONRPCRequestPacket_Request); ok {
		return x.Request
	}
	return nil
}

type isJSONRPCRequestPacket_Payload interface {
	isJSONRPCRequestPacket_Payload()
}

type JSONRPCRequestPacket_MetaRequest struct {
	MetaRequest *MetaRequest `protobuf:"bytes,1,opt,name=meta_request,json=metaRequest,proto3,oneof"`
}

type JSONRPCRequestPacket_Request struct {
	Request *JSONRPCRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

func (*JSONRPCRequestPacket_MetaRequest) isJSONRPCRequestPacket_Payload() {}

func (*JSONRPCRequestPacket_Request) isJSONRPCRequestPacket_Payload() {}

type JSONRPCResultPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JSONRPCResultPacket_MetaResult
	//	*JSONRPCResultPacket_Result
	Payload isJSONRPCResultPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JSONRPCResultPacket) Reset() {
	*x = JSONRPCResultPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCResultPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCResultPacket) ProtoMessage() {}

func (x *JSONRPCResultPacket) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCResultPacket.ProtoReflect.Descriptor instead.
func (*JSONRPCResultPacket) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{13}
}

func (m *JSONRPCResultPacket) GetPayload() isJSONRPCResultPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JSONRPCResultPacket) GetMetaResult() *MetaResult {
	if x, ok := x.GetPayload().(*JSONRPCResultPacket_MetaResult); ok {
		return x.MetaResult
	}
	return nil
}

func (x *JSONRPCResultPacket) GetResult() *JSONRPCResult {
	if x, ok := x.GetPayload().(*JSONRPCResultPacket_Result); ok {
		return x.Result
	}
	return nil
}

type isJSONRPCResultPacket_Payload interface {
	isJSONRPCResultPacket_Payload()
}

type JSONRPCResultPacket_MetaResult struct {
	MetaResult *MetaResult `protobuf:"bytes,1,opt,name=meta_result,json=metaResult,proto3,oneof"`
}

type JSONRPCResultPacket_Result struct {
	Result *JSONRPCResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*JSONRPCResultPacket_MetaResult) isJSONRPCResultPacket_Payload() {}

func (*JSONRPCResultPacket_Result) isJSONRPCResultPacket_Payload() {}

var File_tube_proto protoreflect.FileDescriptor

var file_tube_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x75, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x47, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x44, 0x65, 0x63, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x29,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x19,
	0x0a, 0x17, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0c, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x56, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x23, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x5c, 0x0a, 0x08, 0x52, 0x50,
	0x43, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x52, 0x50, 0x43, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x22, 0x50, 0x0a, 0x0e, 0x4a, 0x53, 0x4f, 0x4e,
	0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x53, 0x0a, 0x0d, 0x4a, 0x53,
	0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x81, 0x01, 0x0a, 0x14, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x31, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x61,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b,
	0x6d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4a,
	0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x7a, 0x0a, 0x13, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x6d, 0x65,
	0x74, 0x61, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0a,
	0x6d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4a, 0x53, 0x4f,
	0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a,
	0x1a, 0x0a, 0x0b, 0x52, 0x50, 0x43, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x0b,
	0x0a, 0x07, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x10, 0x00, 0x32, 0x71, 0x0a, 0x09, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x48, 0x75, 0x62, 0x12, 0x35, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x0c, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x73, 0x44, 0x65, 0x63, 0x6c, 0x1a, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2d, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x6c, 0x6c, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c,
	0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x63, 0x6c, 0x30, 0x01, 0x32, 0xa8,
	0x01, 0x0a, 0x0b, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x54, 0x75, 0x62, 0x65, 0x12, 0x35,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x12, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0f, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39,
	0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52,
	0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x15,
	0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x69, 0x6e, 0x74,
	0x66, 0x2f, 0x74, 0x75, 0x62, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tube_proto_rawDescOnce sync.Once
	file_tube_proto_rawDescData = file_tube_proto_rawDesc
)

func file_tube_proto_rawDescGZIP() []byte {
	file_tube_proto_rawDescOnce.Do(func() {
		file_tube_proto_rawDescData = protoimpl.X.CompressGZIP(file_tube_proto_rawDescData)
	})
	return file_tube_proto_rawDescData
}

var file_tube_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tube_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tube_proto_goTypes = []interface{}{
	(RPCProtocol)(0),                // 0: RPCProtocol
	(*Empty)(nil),                   // 1: Empty
	(*MethodsDecl)(nil),             // 2: MethodsDecl
	(*UpdateMethodsResponse)(nil),   // 3: UpdateMethodsResponse
	(*GetMethodsRequest)(nil),       // 4: GetMethodsRequest
	(*GetMethodsResponse)(nil),      // 5: GetMethodsResponse
	(*SubscribeMethodsRequest)(nil), // 6: SubscribeMethodsRequest
	(*MethodUpdate)(nil),            // 7: MethodUpdate
	(*MetaRequest)(nil),             // 8: MetaRequest
	(*MetaResult)(nil),              // 9: MetaResult
	(*RPCEntry)(nil),                // 10: RPCEntry
	(*JSONRPCRequest)(nil),          // 11: JSONRPCRequest
	(*JSONRPCResult)(nil),           // 12: JSONRPCResult
	(*JSONRPCRequestPacket)(nil),    // 13: JSONRPCRequestPacket
	(*JSONRPCResultPacket)(nil),     // 14: JSONRPCResultPacket
}
var file_tube_proto_depIdxs = []int32{
	10, // 0: MetaResult.entries:type_name -> RPCEntry
	0,  // 1: RPCEntry.protocol:type_name -> RPCProtocol
	8,  // 2: JSONRPCRequestPacket.meta_request:type_name -> MetaRequest
	11, // 3: JSONRPCRequestPacket.request:type_name -> JSONRPCRequest
	9,  // 4: JSONRPCResultPacket.meta_result:type_name -> MetaResult
	12, // 5: JSONRPCResultPacket.result:type_name -> JSONRPCResult
	2,  // 6: MethodHub.UpdateMethods:input_type -> MethodsDecl
	1,  // 7: MethodHub.SubscribeAllMethods:input_type -> Empty
	4,  // 8: JSONRPCTube.GetMethods:input_type -> GetMethodsRequest
	11, // 9: JSONRPCTube.Call:input_type -> JSONRPCRequest
	14, // 10: JSONRPCTube.Handle:input_type -> JSONRPCResultPacket
	3,  // 11: MethodHub.UpdateMethods:output_type -> UpdateMethodsResponse
	2,  // 12: MethodHub.SubscribeAllMethods:output_type -> MethodsDecl
	5,  // 13: JSONRPCTube.GetMethods:output_type -> GetMethodsResponse
	12, // 14: JSONRPCTube.Call:output_type -> JSONRPCResult
	13, // 15: JSONRPCTube.Handle:output_type -> JSONRPCRequestPacket
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tube_proto_init() }
func file_tube_proto_init() {
	if File_tube_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tube_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodsDecl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCRequestPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCResultPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tube_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*JSONRPCResult_Ok)(nil),
		(*JSONRPCResult_Error)(nil),
	}
	file_tube_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*JSONRPCRequestPacket_MetaRequest)(nil),
		(*JSONRPCRequestPacket_Request)(nil),
	}
	file_tube_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*JSONRPCResultPacket_MetaResult)(nil),
		(*JSONRPCResultPacket_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tube_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tube_proto_goTypes,
		DependencyIndexes: file_tube_proto_depIdxs,
		EnumInfos:         file_tube_proto_enumTypes,
		MessageInfos:      file_tube_proto_msgTypes,
	}.Build()
	File_tube_proto = out.File
	file_tube_proto_rawDesc = nil
	file_tube_proto_goTypes = nil
	file_tube_proto_depIdxs = nil
}
