// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: tube.proto

package tube

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCProtocol int32

const (
	RPCProtocol_JSONRPC RPCProtocol = 0
)

// Enum value maps for RPCProtocol.
var (
	RPCProtocol_name = map[int32]string{
		0: "JSONRPC",
	}
	RPCProtocol_value = map[string]int32{
		"JSONRPC": 0,
	}
)

func (x RPCProtocol) Enum() *RPCProtocol {
	p := new(RPCProtocol)
	*p = x
	return p
}

func (x RPCProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPCProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_tube_proto_enumTypes[0].Descriptor()
}

func (RPCProtocol) Type() protoreflect.EnumType {
	return &file_tube_proto_enumTypes[0]
}

func (x RPCProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPCProtocol.Descriptor instead.
func (RPCProtocol) EnumDescriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{0}
}

type ListMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMethodsRequest) Reset() {
	*x = ListMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsRequest) ProtoMessage() {}

func (x *ListMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{1}
}

type ListMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodInfos []*MethodInfo `protobuf:"bytes,1,rep,name=method_infos,json=methodInfos,proto3" json:"method_infos,omitempty"`
}

func (x *ListMethodsResponse) Reset() {
	*x = ListMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsResponse) ProtoMessage() {}

func (x *ListMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListMethodsResponse) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{2}
}

func (x *ListMethodsResponse) GetMethodInfos() []*MethodInfo {
	if x != nil {
		return x.MethodInfos
	}
	return nil
}

type SubscribeMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeMethodsRequest) Reset() {
	*x = SubscribeMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMethodsRequest) ProtoMessage() {}

func (x *SubscribeMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMethodsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{3}
}

type MethodUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *MethodUpdate) Reset() {
	*x = MethodUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodUpdate) ProtoMessage() {}

func (x *MethodUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodUpdate.ProtoReflect.Descriptor instead.
func (*MethodUpdate) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{4}
}

func (x *MethodUpdate) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type MetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{5}
}

type MetaResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries      []*RPCEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	PingInterval int32       `protobuf:"varint,3,opt,name=ping_interval,json=pingInterval,proto3" json:"ping_interval,omitempty"`
}

func (x *MetaResult) Reset() {
	*x = MetaResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResult) ProtoMessage() {}

func (x *MetaResult) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResult.ProtoReflect.Descriptor instead.
func (*MetaResult) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{6}
}

func (x *MetaResult) GetEntries() []*RPCEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *MetaResult) GetPingInterval() int32 {
	if x != nil {
		return x.PingInterval
	}
	return 0
}

type RPCEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol RPCProtocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=RPCProtocol" json:"protocol,omitempty"`
	Name     string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Help     string      `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
}

func (x *RPCEntry) Reset() {
	*x = RPCEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCEntry) ProtoMessage() {}

func (x *RPCEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCEntry.ProtoReflect.Descriptor instead.
func (*RPCEntry) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{7}
}

func (x *RPCEntry) GetProtocol() RPCProtocol {
	if x != nil {
		return x.Protocol
	}
	return RPCProtocol_JSONRPC
}

func (x *RPCEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RPCEntry) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

type JSONRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // empty id means notify
	//int64 id = 1;
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params string `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"` // JSON encoded
}

func (x *JSONRPCRequest) Reset() {
	*x = JSONRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCRequest) ProtoMessage() {}

func (x *JSONRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCRequest.ProtoReflect.Descriptor instead.
func (*JSONRPCRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{8}
}

func (x *JSONRPCRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JSONRPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *JSONRPCRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type JSONRPCResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//int64 id = 1;
	//
	// Types that are assignable to Result:
	//	*JSONRPCResult_Ok
	//	*JSONRPCResult_Error
	Result isJSONRPCResult_Result `protobuf_oneof:"result"`
}

func (x *JSONRPCResult) Reset() {
	*x = JSONRPCResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCResult) ProtoMessage() {}

func (x *JSONRPCResult) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCResult.ProtoReflect.Descriptor instead.
func (*JSONRPCResult) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{9}
}

func (x *JSONRPCResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *JSONRPCResult) GetResult() isJSONRPCResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *JSONRPCResult) GetOk() string {
	if x, ok := x.GetResult().(*JSONRPCResult_Ok); ok {
		return x.Ok
	}
	return ""
}

func (x *JSONRPCResult) GetError() string {
	if x, ok := x.GetResult().(*JSONRPCResult_Error); ok {
		return x.Error
	}
	return ""
}

type isJSONRPCResult_Result interface {
	isJSONRPCResult_Result()
}

type JSONRPCResult_Ok struct {
	Ok string `protobuf:"bytes,10,opt,name=ok,proto3,oneof"` // JSON encoded
}

type JSONRPCResult_Error struct {
	Error string `protobuf:"bytes,11,opt,name=error,proto3,oneof"` // JSON encoded
}

func (*JSONRPCResult_Ok) isJSONRPCResult_Result() {}

func (*JSONRPCResult_Error) isJSONRPCResult_Result() {}

type JSONRPCNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method    string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Params    string `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"` // JSON encoded
	Broadcast bool   `protobuf:"varint,3,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
}

func (x *JSONRPCNotifyRequest) Reset() {
	*x = JSONRPCNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCNotifyRequest) ProtoMessage() {}

func (x *JSONRPCNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCNotifyRequest.ProtoReflect.Descriptor instead.
func (*JSONRPCNotifyRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{10}
}

func (x *JSONRPCNotifyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *JSONRPCNotifyRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *JSONRPCNotifyRequest) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

type JSONRPCNotifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JSONRPCNotifyResponse) Reset() {
	*x = JSONRPCNotifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCNotifyResponse) ProtoMessage() {}

func (x *JSONRPCNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCNotifyResponse.ProtoReflect.Descriptor instead.
func (*JSONRPCNotifyResponse) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{11}
}

type MethodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//MethodLocation location = 2;
	Help       string `protobuf:"bytes,2,opt,name=help,proto3" json:"help,omitempty"`
	SchemaJson string `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	Delegated  bool   `protobuf:"varint,4,opt,name=delegated,proto3" json:"delegated,omitempty"`
}

func (x *MethodInfo) Reset() {
	*x = MethodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodInfo) ProtoMessage() {}

func (x *MethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodInfo.ProtoReflect.Descriptor instead.
func (*MethodInfo) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{12}
}

func (x *MethodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodInfo) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *MethodInfo) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

func (x *MethodInfo) GetDelegated() bool {
	if x != nil {
		return x.Delegated
	}
	return false
}

type UpdateMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []*MethodInfo `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *UpdateMethodsRequest) Reset() {
	*x = UpdateMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMethodsRequest) ProtoMessage() {}

func (x *UpdateMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMethodsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMethodsRequest) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMethodsRequest) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type UpdateMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *UpdateMethodsResponse) Reset() {
	*x = UpdateMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMethodsResponse) ProtoMessage() {}

func (x *UpdateMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMethodsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMethodsResponse) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMethodsResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PING struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PING) Reset() {
	*x = PING{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PING) ProtoMessage() {}

func (x *PING) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PING.ProtoReflect.Descriptor instead.
func (*PING) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{15}
}

func (x *PING) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PONG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PONG) Reset() {
	*x = PONG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PONG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PONG) ProtoMessage() {}

func (x *PONG) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PONG.ProtoReflect.Descriptor instead.
func (*PONG) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{16}
}

func (x *PONG) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type JSONRPCDownPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JSONRPCDownPacket_UpdateMethods
	//	*JSONRPCDownPacket_Ping
	//	*JSONRPCDownPacket_Pong
	//	*JSONRPCDownPacket_Request
	//	*JSONRPCDownPacket_Result
	Payload isJSONRPCDownPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JSONRPCDownPacket) Reset() {
	*x = JSONRPCDownPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCDownPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCDownPacket) ProtoMessage() {}

func (x *JSONRPCDownPacket) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCDownPacket.ProtoReflect.Descriptor instead.
func (*JSONRPCDownPacket) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{17}
}

func (m *JSONRPCDownPacket) GetPayload() isJSONRPCDownPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JSONRPCDownPacket) GetUpdateMethods() *UpdateMethodsResponse {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_UpdateMethods); ok {
		return x.UpdateMethods
	}
	return nil
}

func (x *JSONRPCDownPacket) GetPing() *PING {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *JSONRPCDownPacket) GetPong() *PONG {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *JSONRPCDownPacket) GetRequest() *JSONRPCRequest {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_Request); ok {
		return x.Request
	}
	return nil
}

func (x *JSONRPCDownPacket) GetResult() *JSONRPCResult {
	if x, ok := x.GetPayload().(*JSONRPCDownPacket_Result); ok {
		return x.Result
	}
	return nil
}

type isJSONRPCDownPacket_Payload interface {
	isJSONRPCDownPacket_Payload()
}

type JSONRPCDownPacket_UpdateMethods struct {
	UpdateMethods *UpdateMethodsResponse `protobuf:"bytes,1,opt,name=update_methods,json=updateMethods,proto3,oneof"`
}

type JSONRPCDownPacket_Ping struct {
	Ping *PING `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type JSONRPCDownPacket_Pong struct {
	Pong *PONG `protobuf:"bytes,11,opt,name=pong,proto3,oneof"`
}

type JSONRPCDownPacket_Request struct {
	Request *JSONRPCRequest `protobuf:"bytes,20,opt,name=request,proto3,oneof"`
}

type JSONRPCDownPacket_Result struct {
	Result *JSONRPCResult `protobuf:"bytes,21,opt,name=result,proto3,oneof"`
}

func (*JSONRPCDownPacket_UpdateMethods) isJSONRPCDownPacket_Payload() {}

func (*JSONRPCDownPacket_Ping) isJSONRPCDownPacket_Payload() {}

func (*JSONRPCDownPacket_Pong) isJSONRPCDownPacket_Payload() {}

func (*JSONRPCDownPacket_Request) isJSONRPCDownPacket_Payload() {}

func (*JSONRPCDownPacket_Result) isJSONRPCDownPacket_Payload() {}

type JSONRPCUpPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JSONRPCUpPacket_UpdateMethods
	//	*JSONRPCUpPacket_Ping
	//	*JSONRPCUpPacket_Pong
	//	*JSONRPCUpPacket_Request
	//	*JSONRPCUpPacket_Result
	Payload isJSONRPCUpPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JSONRPCUpPacket) Reset() {
	*x = JSONRPCUpPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tube_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCUpPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCUpPacket) ProtoMessage() {}

func (x *JSONRPCUpPacket) ProtoReflect() protoreflect.Message {
	mi := &file_tube_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCUpPacket.ProtoReflect.Descriptor instead.
func (*JSONRPCUpPacket) Descriptor() ([]byte, []int) {
	return file_tube_proto_rawDescGZIP(), []int{18}
}

func (m *JSONRPCUpPacket) GetPayload() isJSONRPCUpPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JSONRPCUpPacket) GetUpdateMethods() *UpdateMethodsRequest {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_UpdateMethods); ok {
		return x.UpdateMethods
	}
	return nil
}

func (x *JSONRPCUpPacket) GetPing() *PING {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *JSONRPCUpPacket) GetPong() *PONG {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *JSONRPCUpPacket) GetRequest() *JSONRPCRequest {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_Request); ok {
		return x.Request
	}
	return nil
}

func (x *JSONRPCUpPacket) GetResult() *JSONRPCResult {
	if x, ok := x.GetPayload().(*JSONRPCUpPacket_Result); ok {
		return x.Result
	}
	return nil
}

type isJSONRPCUpPacket_Payload interface {
	isJSONRPCUpPacket_Payload()
}

type JSONRPCUpPacket_UpdateMethods struct {
	UpdateMethods *UpdateMethodsRequest `protobuf:"bytes,1,opt,name=update_methods,json=updateMethods,proto3,oneof"`
}

type JSONRPCUpPacket_Ping struct {
	Ping *PING `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type JSONRPCUpPacket_Pong struct {
	Pong *PONG `protobuf:"bytes,11,opt,name=pong,proto3,oneof"`
}

type JSONRPCUpPacket_Request struct {
	Request *JSONRPCRequest `protobuf:"bytes,20,opt,name=request,proto3,oneof"`
}

type JSONRPCUpPacket_Result struct {
	Result *JSONRPCResult `protobuf:"bytes,21,opt,name=result,proto3,oneof"`
}

func (*JSONRPCUpPacket_UpdateMethods) isJSONRPCUpPacket_Payload() {}

func (*JSONRPCUpPacket_Ping) isJSONRPCUpPacket_Payload() {}

func (*JSONRPCUpPacket_Pong) isJSONRPCUpPacket_Payload() {}

func (*JSONRPCUpPacket_Request) isJSONRPCUpPacket_Payload() {}

func (*JSONRPCUpPacket_Result) isJSONRPCUpPacket_Payload() {}

var File_tube_proto protoreflect.FileDescriptor

var file_tube_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x75, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a,
	0x0c, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x5c,
	0x0a, 0x08, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x52,
	0x50, 0x43, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x22, 0x50, 0x0a, 0x0e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x53,
	0x0a, 0x0d, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x64, 0x0a, 0x14, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x4a, 0x53, 0x4f,
	0x4e, 0x52, 0x50, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x73, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x65,
	0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x22, 0x3d, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x1a, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xf0, 0x01, 0x0a, 0x11,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x44, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x3f, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x50, 0x49, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12,
	0x1b, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x50, 0x4f, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4a, 0x53, 0x4f, 0x4e,
	0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xed,
	0x01, 0x0a, 0x0f, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x55, 0x70, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x50, 0x49, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12,
	0x1b, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x50, 0x4f, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4a, 0x53, 0x4f, 0x4e,
	0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x1a,
	0x0a, 0x0b, 0x52, 0x50, 0x43, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x0b, 0x0a,
	0x07, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x10, 0x00, 0x32, 0xdd, 0x01, 0x0a, 0x0b, 0x4a,
	0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x54, 0x75, 0x62, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0f, 0x2e, 0x4a,
	0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x37, 0x0a,
	0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x15, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50,
	0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x12, 0x10, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x55, 0x70, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x1a, 0x12, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x44, 0x6f, 0x77, 0x6e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x69, 0x6e,
	0x74, 0x66, 0x2f, 0x74, 0x75, 0x62, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tube_proto_rawDescOnce sync.Once
	file_tube_proto_rawDescData = file_tube_proto_rawDesc
)

func file_tube_proto_rawDescGZIP() []byte {
	file_tube_proto_rawDescOnce.Do(func() {
		file_tube_proto_rawDescData = protoimpl.X.CompressGZIP(file_tube_proto_rawDescData)
	})
	return file_tube_proto_rawDescData
}

var file_tube_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tube_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_tube_proto_goTypes = []interface{}{
	(RPCProtocol)(0),                // 0: RPCProtocol
	(*Empty)(nil),                   // 1: Empty
	(*ListMethodsRequest)(nil),      // 2: ListMethodsRequest
	(*ListMethodsResponse)(nil),     // 3: ListMethodsResponse
	(*SubscribeMethodsRequest)(nil), // 4: SubscribeMethodsRequest
	(*MethodUpdate)(nil),            // 5: MethodUpdate
	(*MetaRequest)(nil),             // 6: MetaRequest
	(*MetaResult)(nil),              // 7: MetaResult
	(*RPCEntry)(nil),                // 8: RPCEntry
	(*JSONRPCRequest)(nil),          // 9: JSONRPCRequest
	(*JSONRPCResult)(nil),           // 10: JSONRPCResult
	(*JSONRPCNotifyRequest)(nil),    // 11: JSONRPCNotifyRequest
	(*JSONRPCNotifyResponse)(nil),   // 12: JSONRPCNotifyResponse
	(*MethodInfo)(nil),              // 13: MethodInfo
	(*UpdateMethodsRequest)(nil),    // 14: UpdateMethodsRequest
	(*UpdateMethodsResponse)(nil),   // 15: UpdateMethodsResponse
	(*PING)(nil),                    // 16: PING
	(*PONG)(nil),                    // 17: PONG
	(*JSONRPCDownPacket)(nil),       // 18: JSONRPCDownPacket
	(*JSONRPCUpPacket)(nil),         // 19: JSONRPCUpPacket
}
var file_tube_proto_depIdxs = []int32{
	13, // 0: ListMethodsResponse.method_infos:type_name -> MethodInfo
	8,  // 1: MetaResult.entries:type_name -> RPCEntry
	0,  // 2: RPCEntry.protocol:type_name -> RPCProtocol
	13, // 3: UpdateMethodsRequest.methods:type_name -> MethodInfo
	15, // 4: JSONRPCDownPacket.update_methods:type_name -> UpdateMethodsResponse
	16, // 5: JSONRPCDownPacket.ping:type_name -> PING
	17, // 6: JSONRPCDownPacket.pong:type_name -> PONG
	9,  // 7: JSONRPCDownPacket.request:type_name -> JSONRPCRequest
	10, // 8: JSONRPCDownPacket.result:type_name -> JSONRPCResult
	14, // 9: JSONRPCUpPacket.update_methods:type_name -> UpdateMethodsRequest
	16, // 10: JSONRPCUpPacket.ping:type_name -> PING
	17, // 11: JSONRPCUpPacket.pong:type_name -> PONG
	9,  // 12: JSONRPCUpPacket.request:type_name -> JSONRPCRequest
	10, // 13: JSONRPCUpPacket.result:type_name -> JSONRPCResult
	2,  // 14: JSONRPCTube.ListMethods:input_type -> ListMethodsRequest
	9,  // 15: JSONRPCTube.Call:input_type -> JSONRPCRequest
	11, // 16: JSONRPCTube.Notify:input_type -> JSONRPCNotifyRequest
	19, // 17: JSONRPCTube.Handle:input_type -> JSONRPCUpPacket
	3,  // 18: JSONRPCTube.ListMethods:output_type -> ListMethodsResponse
	10, // 19: JSONRPCTube.Call:output_type -> JSONRPCResult
	12, // 20: JSONRPCTube.Notify:output_type -> JSONRPCNotifyResponse
	18, // 21: JSONRPCTube.Handle:output_type -> JSONRPCDownPacket
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_tube_proto_init() }
func file_tube_proto_init() {
	if File_tube_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tube_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCNotifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PING); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PONG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCDownPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tube_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCUpPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tube_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*JSONRPCResult_Ok)(nil),
		(*JSONRPCResult_Error)(nil),
	}
	file_tube_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*JSONRPCDownPacket_UpdateMethods)(nil),
		(*JSONRPCDownPacket_Ping)(nil),
		(*JSONRPCDownPacket_Pong)(nil),
		(*JSONRPCDownPacket_Request)(nil),
		(*JSONRPCDownPacket_Result)(nil),
	}
	file_tube_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*JSONRPCUpPacket_UpdateMethods)(nil),
		(*JSONRPCUpPacket_Ping)(nil),
		(*JSONRPCUpPacket_Pong)(nil),
		(*JSONRPCUpPacket_Request)(nil),
		(*JSONRPCUpPacket_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tube_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tube_proto_goTypes,
		DependencyIndexes: file_tube_proto_depIdxs,
		EnumInfos:         file_tube_proto_enumTypes,
		MessageInfos:      file_tube_proto_msgTypes,
	}.Build()
	File_tube_proto = out.File
	file_tube_proto_rawDesc = nil
	file_tube_proto_goTypes = nil
	file_tube_proto_depIdxs = nil
}
