# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tube_pb2 as tube__pb2


class JSONRPCTubeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMethods = channel.unary_unary(
                '/JSONRPCTube/ListMethods',
                request_serializer=tube__pb2.ListMethodsRequest.SerializeToString,
                response_deserializer=tube__pb2.ListMethodsResponse.FromString,
                )
        self.WatchMethods = channel.unary_stream(
                '/JSONRPCTube/WatchMethods',
                request_serializer=tube__pb2.WatchMethodsRequest.SerializeToString,
                response_deserializer=tube__pb2.MethodUpdate.FromString,
                )
        self.Call = channel.unary_unary(
                '/JSONRPCTube/Call',
                request_serializer=tube__pb2.JSONRPCCallRequest.SerializeToString,
                response_deserializer=tube__pb2.JSONRPCCallResult.FromString,
                )
        self.Notify = channel.unary_unary(
                '/JSONRPCTube/Notify',
                request_serializer=tube__pb2.JSONRPCNotifyRequest.SerializeToString,
                response_deserializer=tube__pb2.JSONRPCNotifyResponse.FromString,
                )
        self.Handle = channel.stream_stream(
                '/JSONRPCTube/Handle',
                request_serializer=tube__pb2.JSONRPCUpPacket.SerializeToString,
                response_deserializer=tube__pb2.JSONRPCDownPacket.FromString,
                )


class JSONRPCTubeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListMethods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchMethods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Handle(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JSONRPCTubeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMethods,
                    request_deserializer=tube__pb2.ListMethodsRequest.FromString,
                    response_serializer=tube__pb2.ListMethodsResponse.SerializeToString,
            ),
            'WatchMethods': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchMethods,
                    request_deserializer=tube__pb2.WatchMethodsRequest.FromString,
                    response_serializer=tube__pb2.MethodUpdate.SerializeToString,
            ),
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=tube__pb2.JSONRPCCallRequest.FromString,
                    response_serializer=tube__pb2.JSONRPCCallResult.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=tube__pb2.JSONRPCNotifyRequest.FromString,
                    response_serializer=tube__pb2.JSONRPCNotifyResponse.SerializeToString,
            ),
            'Handle': grpc.stream_stream_rpc_method_handler(
                    servicer.Handle,
                    request_deserializer=tube__pb2.JSONRPCUpPacket.FromString,
                    response_serializer=tube__pb2.JSONRPCDownPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JSONRPCTube', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JSONRPCTube(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JSONRPCTube/ListMethods',
            tube__pb2.ListMethodsRequest.SerializeToString,
            tube__pb2.ListMethodsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/JSONRPCTube/WatchMethods',
            tube__pb2.WatchMethodsRequest.SerializeToString,
            tube__pb2.MethodUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JSONRPCTube/Call',
            tube__pb2.JSONRPCCallRequest.SerializeToString,
            tube__pb2.JSONRPCCallResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JSONRPCTube/Notify',
            tube__pb2.JSONRPCNotifyRequest.SerializeToString,
            tube__pb2.JSONRPCNotifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Handle(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/JSONRPCTube/Handle',
            tube__pb2.JSONRPCUpPacket.SerializeToString,
            tube__pb2.JSONRPCDownPacket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
