# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tube.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tube.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\tintf/tube',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntube.proto\"\x07\n\x05\x45mpty\"2\n\x0bMethodsDecl\x12\x12\n\nentrypoint\x18\x01 \x01(\t\x12\x0f\n\x07methods\x18\x02 \x03(\t\"$\n\x15UpdateMethodsResponse\x12\x0b\n\x03res\x18\x01 \x01(\t\"\x13\n\x11GetMethodsRequest\"%\n\x12GetMethodsResponse\x12\x0f\n\x07methods\x18\x01 \x03(\t\"\x19\n\x17SubscribeMethodsRequest\"\x1f\n\x0cMethodUpdate\x12\x0f\n\x07methods\x18\x01 \x03(\t\"\r\n\x0bMetaRequest\"?\n\nMetaResult\x12\x1a\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\t.RPCEntry\x12\x15\n\rping_interval\x18\x03 \x01(\x05\"F\n\x08RPCEntry\x12\x1e\n\x08protocol\x18\x01 \x01(\x0e\x32\x0c.RPCProtocol\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04help\x18\x03 \x01(\t\"<\n\x0eJSONRPCRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0e\n\x06params\x18\x03 \x01(\t\"D\n\rJSONRPCResult\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x02ok\x18\n \x01(\tH\x00\x12\x0f\n\x05\x65rror\x18\x0b \x01(\tH\x00\x42\x08\n\x06result\"k\n\x14JSONRPCRequestPacket\x12$\n\x0cmeta_request\x18\x01 \x01(\x0b\x32\x0c.MetaRequestH\x00\x12\"\n\x07request\x18\x02 \x01(\x0b\x32\x0f.JSONRPCRequestH\x00\x42\t\n\x07payload\"f\n\x13JSONRPCResultPacket\x12\"\n\x0bmeta_result\x18\x01 \x01(\x0b\x32\x0b.MetaResultH\x00\x12 \n\x06result\x18\x02 \x01(\x0b\x32\x0e.JSONRPCResultH\x00\x42\t\n\x07payload*\x1a\n\x0bRPCProtocol\x12\x0b\n\x07JSONRPC\x10\x00\x32q\n\tMethodHub\x12\x35\n\rUpdateMethods\x12\x0c.MethodsDecl\x1a\x16.UpdateMethodsResponse\x12-\n\x13SubscribeAllMethods\x12\x06.Empty\x1a\x0c.MethodsDecl0\x01\x32\xa8\x01\n\x0bJSONRPCTube\x12\x35\n\nGetMethods\x12\x12.GetMethodsRequest\x1a\x13.GetMethodsResponse\x12\'\n\x04\x43\x61ll\x12\x0f.JSONRPCRequest\x1a\x0e.JSONRPCResult\x12\x39\n\x06Handle\x12\x14.JSONRPCResultPacket\x1a\x15.JSONRPCRequestPacket(\x01\x30\x01\x42\x0bZ\tintf/tubeb\x06proto3'
)

_RPCPROTOCOL = _descriptor.EnumDescriptor(
  name='RPCProtocol',
  full_name='RPCProtocol',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JSONRPC', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=730,
  serialized_end=756,
)
_sym_db.RegisterEnumDescriptor(_RPCPROTOCOL)

RPCProtocol = enum_type_wrapper.EnumTypeWrapper(_RPCPROTOCOL)
JSONRPC = 0



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=21,
)


_METHODSDECL = _descriptor.Descriptor(
  name='MethodsDecl',
  full_name='MethodsDecl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entrypoint', full_name='MethodsDecl.entrypoint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='methods', full_name='MethodsDecl.methods', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=73,
)


_UPDATEMETHODSRESPONSE = _descriptor.Descriptor(
  name='UpdateMethodsResponse',
  full_name='UpdateMethodsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='UpdateMethodsResponse.res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=111,
)


_GETMETHODSREQUEST = _descriptor.Descriptor(
  name='GetMethodsRequest',
  full_name='GetMethodsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=132,
)


_GETMETHODSRESPONSE = _descriptor.Descriptor(
  name='GetMethodsResponse',
  full_name='GetMethodsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='methods', full_name='GetMethodsResponse.methods', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=171,
)


_SUBSCRIBEMETHODSREQUEST = _descriptor.Descriptor(
  name='SubscribeMethodsRequest',
  full_name='SubscribeMethodsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=198,
)


_METHODUPDATE = _descriptor.Descriptor(
  name='MethodUpdate',
  full_name='MethodUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='methods', full_name='MethodUpdate.methods', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=231,
)


_METAREQUEST = _descriptor.Descriptor(
  name='MetaRequest',
  full_name='MetaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=246,
)


_METARESULT = _descriptor.Descriptor(
  name='MetaResult',
  full_name='MetaResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='MetaResult.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ping_interval', full_name='MetaResult.ping_interval', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=311,
)


_RPCENTRY = _descriptor.Descriptor(
  name='RPCEntry',
  full_name='RPCEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol', full_name='RPCEntry.protocol', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='RPCEntry.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='help', full_name='RPCEntry.help', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=383,
)


_JSONRPCREQUEST = _descriptor.Descriptor(
  name='JSONRPCRequest',
  full_name='JSONRPCRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='JSONRPCRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='JSONRPCRequest.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='JSONRPCRequest.params', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=445,
)


_JSONRPCRESULT = _descriptor.Descriptor(
  name='JSONRPCResult',
  full_name='JSONRPCResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='JSONRPCResult.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ok', full_name='JSONRPCResult.ok', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='JSONRPCResult.error', index=2,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='JSONRPCResult.result',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=447,
  serialized_end=515,
)


_JSONRPCREQUESTPACKET = _descriptor.Descriptor(
  name='JSONRPCRequestPacket',
  full_name='JSONRPCRequestPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta_request', full_name='JSONRPCRequestPacket.meta_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='JSONRPCRequestPacket.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='JSONRPCRequestPacket.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=517,
  serialized_end=624,
)


_JSONRPCRESULTPACKET = _descriptor.Descriptor(
  name='JSONRPCResultPacket',
  full_name='JSONRPCResultPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta_result', full_name='JSONRPCResultPacket.meta_result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='JSONRPCResultPacket.result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='JSONRPCResultPacket.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=626,
  serialized_end=728,
)

_METARESULT.fields_by_name['entries'].message_type = _RPCENTRY
_RPCENTRY.fields_by_name['protocol'].enum_type = _RPCPROTOCOL
_JSONRPCRESULT.oneofs_by_name['result'].fields.append(
  _JSONRPCRESULT.fields_by_name['ok'])
_JSONRPCRESULT.fields_by_name['ok'].containing_oneof = _JSONRPCRESULT.oneofs_by_name['result']
_JSONRPCRESULT.oneofs_by_name['result'].fields.append(
  _JSONRPCRESULT.fields_by_name['error'])
_JSONRPCRESULT.fields_by_name['error'].containing_oneof = _JSONRPCRESULT.oneofs_by_name['result']
_JSONRPCREQUESTPACKET.fields_by_name['meta_request'].message_type = _METAREQUEST
_JSONRPCREQUESTPACKET.fields_by_name['request'].message_type = _JSONRPCREQUEST
_JSONRPCREQUESTPACKET.oneofs_by_name['payload'].fields.append(
  _JSONRPCREQUESTPACKET.fields_by_name['meta_request'])
_JSONRPCREQUESTPACKET.fields_by_name['meta_request'].containing_oneof = _JSONRPCREQUESTPACKET.oneofs_by_name['payload']
_JSONRPCREQUESTPACKET.oneofs_by_name['payload'].fields.append(
  _JSONRPCREQUESTPACKET.fields_by_name['request'])
_JSONRPCREQUESTPACKET.fields_by_name['request'].containing_oneof = _JSONRPCREQUESTPACKET.oneofs_by_name['payload']
_JSONRPCRESULTPACKET.fields_by_name['meta_result'].message_type = _METARESULT
_JSONRPCRESULTPACKET.fields_by_name['result'].message_type = _JSONRPCRESULT
_JSONRPCRESULTPACKET.oneofs_by_name['payload'].fields.append(
  _JSONRPCRESULTPACKET.fields_by_name['meta_result'])
_JSONRPCRESULTPACKET.fields_by_name['meta_result'].containing_oneof = _JSONRPCRESULTPACKET.oneofs_by_name['payload']
_JSONRPCRESULTPACKET.oneofs_by_name['payload'].fields.append(
  _JSONRPCRESULTPACKET.fields_by_name['result'])
_JSONRPCRESULTPACKET.fields_by_name['result'].containing_oneof = _JSONRPCRESULTPACKET.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['MethodsDecl'] = _METHODSDECL
DESCRIPTOR.message_types_by_name['UpdateMethodsResponse'] = _UPDATEMETHODSRESPONSE
DESCRIPTOR.message_types_by_name['GetMethodsRequest'] = _GETMETHODSREQUEST
DESCRIPTOR.message_types_by_name['GetMethodsResponse'] = _GETMETHODSRESPONSE
DESCRIPTOR.message_types_by_name['SubscribeMethodsRequest'] = _SUBSCRIBEMETHODSREQUEST
DESCRIPTOR.message_types_by_name['MethodUpdate'] = _METHODUPDATE
DESCRIPTOR.message_types_by_name['MetaRequest'] = _METAREQUEST
DESCRIPTOR.message_types_by_name['MetaResult'] = _METARESULT
DESCRIPTOR.message_types_by_name['RPCEntry'] = _RPCENTRY
DESCRIPTOR.message_types_by_name['JSONRPCRequest'] = _JSONRPCREQUEST
DESCRIPTOR.message_types_by_name['JSONRPCResult'] = _JSONRPCRESULT
DESCRIPTOR.message_types_by_name['JSONRPCRequestPacket'] = _JSONRPCREQUESTPACKET
DESCRIPTOR.message_types_by_name['JSONRPCResultPacket'] = _JSONRPCRESULTPACKET
DESCRIPTOR.enum_types_by_name['RPCProtocol'] = _RPCPROTOCOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

MethodsDecl = _reflection.GeneratedProtocolMessageType('MethodsDecl', (_message.Message,), {
  'DESCRIPTOR' : _METHODSDECL,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:MethodsDecl)
  })
_sym_db.RegisterMessage(MethodsDecl)

UpdateMethodsResponse = _reflection.GeneratedProtocolMessageType('UpdateMethodsResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMETHODSRESPONSE,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:UpdateMethodsResponse)
  })
_sym_db.RegisterMessage(UpdateMethodsResponse)

GetMethodsRequest = _reflection.GeneratedProtocolMessageType('GetMethodsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMETHODSREQUEST,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:GetMethodsRequest)
  })
_sym_db.RegisterMessage(GetMethodsRequest)

GetMethodsResponse = _reflection.GeneratedProtocolMessageType('GetMethodsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMETHODSRESPONSE,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:GetMethodsResponse)
  })
_sym_db.RegisterMessage(GetMethodsResponse)

SubscribeMethodsRequest = _reflection.GeneratedProtocolMessageType('SubscribeMethodsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEMETHODSREQUEST,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:SubscribeMethodsRequest)
  })
_sym_db.RegisterMessage(SubscribeMethodsRequest)

MethodUpdate = _reflection.GeneratedProtocolMessageType('MethodUpdate', (_message.Message,), {
  'DESCRIPTOR' : _METHODUPDATE,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:MethodUpdate)
  })
_sym_db.RegisterMessage(MethodUpdate)

MetaRequest = _reflection.GeneratedProtocolMessageType('MetaRequest', (_message.Message,), {
  'DESCRIPTOR' : _METAREQUEST,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:MetaRequest)
  })
_sym_db.RegisterMessage(MetaRequest)

MetaResult = _reflection.GeneratedProtocolMessageType('MetaResult', (_message.Message,), {
  'DESCRIPTOR' : _METARESULT,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:MetaResult)
  })
_sym_db.RegisterMessage(MetaResult)

RPCEntry = _reflection.GeneratedProtocolMessageType('RPCEntry', (_message.Message,), {
  'DESCRIPTOR' : _RPCENTRY,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:RPCEntry)
  })
_sym_db.RegisterMessage(RPCEntry)

JSONRPCRequest = _reflection.GeneratedProtocolMessageType('JSONRPCRequest', (_message.Message,), {
  'DESCRIPTOR' : _JSONRPCREQUEST,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:JSONRPCRequest)
  })
_sym_db.RegisterMessage(JSONRPCRequest)

JSONRPCResult = _reflection.GeneratedProtocolMessageType('JSONRPCResult', (_message.Message,), {
  'DESCRIPTOR' : _JSONRPCRESULT,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:JSONRPCResult)
  })
_sym_db.RegisterMessage(JSONRPCResult)

JSONRPCRequestPacket = _reflection.GeneratedProtocolMessageType('JSONRPCRequestPacket', (_message.Message,), {
  'DESCRIPTOR' : _JSONRPCREQUESTPACKET,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:JSONRPCRequestPacket)
  })
_sym_db.RegisterMessage(JSONRPCRequestPacket)

JSONRPCResultPacket = _reflection.GeneratedProtocolMessageType('JSONRPCResultPacket', (_message.Message,), {
  'DESCRIPTOR' : _JSONRPCRESULTPACKET,
  '__module__' : 'tube_pb2'
  # @@protoc_insertion_point(class_scope:JSONRPCResultPacket)
  })
_sym_db.RegisterMessage(JSONRPCResultPacket)


DESCRIPTOR._options = None

_METHODHUB = _descriptor.ServiceDescriptor(
  name='MethodHub',
  full_name='MethodHub',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=758,
  serialized_end=871,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateMethods',
    full_name='MethodHub.UpdateMethods',
    index=0,
    containing_service=None,
    input_type=_METHODSDECL,
    output_type=_UPDATEMETHODSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeAllMethods',
    full_name='MethodHub.SubscribeAllMethods',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_METHODSDECL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METHODHUB)

DESCRIPTOR.services_by_name['MethodHub'] = _METHODHUB


_JSONRPCTUBE = _descriptor.ServiceDescriptor(
  name='JSONRPCTube',
  full_name='JSONRPCTube',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=874,
  serialized_end=1042,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMethods',
    full_name='JSONRPCTube.GetMethods',
    index=0,
    containing_service=None,
    input_type=_GETMETHODSREQUEST,
    output_type=_GETMETHODSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='JSONRPCTube.Call',
    index=1,
    containing_service=None,
    input_type=_JSONRPCREQUEST,
    output_type=_JSONRPCRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Handle',
    full_name='JSONRPCTube.Handle',
    index=2,
    containing_service=None,
    input_type=_JSONRPCRESULTPACKET,
    output_type=_JSONRPCREQUESTPACKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JSONRPCTUBE)

DESCRIPTOR.services_by_name['JSONRPCTube'] = _JSONRPCTUBE

# @@protoc_insertion_point(module_scope)
