# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: jointrpc.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from jointrpc.pb import jointrpc_pb2


class JointRPCBase(abc.ABC):

    @abc.abstractmethod
    async def Call(self, stream: 'grpclib.server.Stream[jointrpc_pb2.JSONRPCCallRequest, jointrpc_pb2.JSONRPCCallResult]') -> None:
        pass

    @abc.abstractmethod
    async def Notify(self, stream: 'grpclib.server.Stream[jointrpc_pb2.JSONRPCNotifyRequest, jointrpc_pb2.JSONRPCNotifyResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ListMethods(self, stream: 'grpclib.server.Stream[jointrpc_pb2.ListMethodsRequest, jointrpc_pb2.ListMethodsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ListDelegates(self, stream: 'grpclib.server.Stream[jointrpc_pb2.ListDelegatesRequest, jointrpc_pb2.ListDelegatesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Live(self, stream: 'grpclib.server.Stream[jointrpc_pb2.JSONRPCEnvolope, jointrpc_pb2.JSONRPCEnvolope]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/JointRPC/Call': grpclib.const.Handler(
                self.Call,
                grpclib.const.Cardinality.UNARY_UNARY,
                jointrpc_pb2.JSONRPCCallRequest,
                jointrpc_pb2.JSONRPCCallResult,
            ),
            '/JointRPC/Notify': grpclib.const.Handler(
                self.Notify,
                grpclib.const.Cardinality.UNARY_UNARY,
                jointrpc_pb2.JSONRPCNotifyRequest,
                jointrpc_pb2.JSONRPCNotifyResponse,
            ),
            '/JointRPC/ListMethods': grpclib.const.Handler(
                self.ListMethods,
                grpclib.const.Cardinality.UNARY_UNARY,
                jointrpc_pb2.ListMethodsRequest,
                jointrpc_pb2.ListMethodsResponse,
            ),
            '/JointRPC/ListDelegates': grpclib.const.Handler(
                self.ListDelegates,
                grpclib.const.Cardinality.UNARY_UNARY,
                jointrpc_pb2.ListDelegatesRequest,
                jointrpc_pb2.ListDelegatesResponse,
            ),
            '/JointRPC/Live': grpclib.const.Handler(
                self.Live,
                grpclib.const.Cardinality.STREAM_STREAM,
                jointrpc_pb2.JSONRPCEnvolope,
                jointrpc_pb2.JSONRPCEnvolope,
            ),
        }


class JointRPCStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Call = grpclib.client.UnaryUnaryMethod(
            channel,
            '/JointRPC/Call',
            jointrpc_pb2.JSONRPCCallRequest,
            jointrpc_pb2.JSONRPCCallResult,
        )
        self.Notify = grpclib.client.UnaryUnaryMethod(
            channel,
            '/JointRPC/Notify',
            jointrpc_pb2.JSONRPCNotifyRequest,
            jointrpc_pb2.JSONRPCNotifyResponse,
        )
        self.ListMethods = grpclib.client.UnaryUnaryMethod(
            channel,
            '/JointRPC/ListMethods',
            jointrpc_pb2.ListMethodsRequest,
            jointrpc_pb2.ListMethodsResponse,
        )
        self.ListDelegates = grpclib.client.UnaryUnaryMethod(
            channel,
            '/JointRPC/ListDelegates',
            jointrpc_pb2.ListDelegatesRequest,
            jointrpc_pb2.ListDelegatesResponse,
        )
        self.Live = grpclib.client.StreamStreamMethod(
            channel,
            '/JointRPC/Live',
            jointrpc_pb2.JSONRPCEnvolope,
            jointrpc_pb2.JSONRPCEnvolope,
        )
