// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package jointrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// JointRPCClient is the client API for JointRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JointRPCClient interface {
	ListMethods(ctx context.Context, in *ListMethodsRequest, opts ...grpc.CallOption) (*ListMethodsResponse, error)
	ListDelegates(ctx context.Context, in *ListDelegatesRequest, opts ...grpc.CallOption) (*ListDelegatesResponse, error)
	DeclareMethods(ctx context.Context, in *DeclareMethodsRequest, opts ...grpc.CallOption) (*DeclareMethodsResponse, error)
	Call(ctx context.Context, in *JSONRPCCallRequest, opts ...grpc.CallOption) (*JSONRPCCallResult, error)
	Notify(ctx context.Context, in *JSONRPCNotifyRequest, opts ...grpc.CallOption) (*JSONRPCNotifyResponse, error)
	Handle(ctx context.Context, opts ...grpc.CallOption) (JointRPC_HandleClient, error)
	// cluster aware RPCs
	DeclareDelegates(ctx context.Context, in *DeclareDelegatesRequest, opts ...grpc.CallOption) (*DeclareDelegatesResponse, error)
}

type jointRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewJointRPCClient(cc grpc.ClientConnInterface) JointRPCClient {
	return &jointRPCClient{cc}
}

func (c *jointRPCClient) ListMethods(ctx context.Context, in *ListMethodsRequest, opts ...grpc.CallOption) (*ListMethodsResponse, error) {
	out := new(ListMethodsResponse)
	err := c.cc.Invoke(ctx, "/JointRPC/ListMethods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointRPCClient) ListDelegates(ctx context.Context, in *ListDelegatesRequest, opts ...grpc.CallOption) (*ListDelegatesResponse, error) {
	out := new(ListDelegatesResponse)
	err := c.cc.Invoke(ctx, "/JointRPC/ListDelegates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointRPCClient) DeclareMethods(ctx context.Context, in *DeclareMethodsRequest, opts ...grpc.CallOption) (*DeclareMethodsResponse, error) {
	out := new(DeclareMethodsResponse)
	err := c.cc.Invoke(ctx, "/JointRPC/DeclareMethods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointRPCClient) Call(ctx context.Context, in *JSONRPCCallRequest, opts ...grpc.CallOption) (*JSONRPCCallResult, error) {
	out := new(JSONRPCCallResult)
	err := c.cc.Invoke(ctx, "/JointRPC/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointRPCClient) Notify(ctx context.Context, in *JSONRPCNotifyRequest, opts ...grpc.CallOption) (*JSONRPCNotifyResponse, error) {
	out := new(JSONRPCNotifyResponse)
	err := c.cc.Invoke(ctx, "/JointRPC/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jointRPCClient) Handle(ctx context.Context, opts ...grpc.CallOption) (JointRPC_HandleClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JointRPC_serviceDesc.Streams[0], "/JointRPC/Handle", opts...)
	if err != nil {
		return nil, err
	}
	x := &jointRPCHandleClient{stream}
	return x, nil
}

type JointRPC_HandleClient interface {
	Send(*JointRPCUpPacket) error
	Recv() (*JointRPCDownPacket, error)
	grpc.ClientStream
}

type jointRPCHandleClient struct {
	grpc.ClientStream
}

func (x *jointRPCHandleClient) Send(m *JointRPCUpPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *jointRPCHandleClient) Recv() (*JointRPCDownPacket, error) {
	m := new(JointRPCDownPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jointRPCClient) DeclareDelegates(ctx context.Context, in *DeclareDelegatesRequest, opts ...grpc.CallOption) (*DeclareDelegatesResponse, error) {
	out := new(DeclareDelegatesResponse)
	err := c.cc.Invoke(ctx, "/JointRPC/DeclareDelegates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JointRPCServer is the server API for JointRPC service.
// All implementations must embed UnimplementedJointRPCServer
// for forward compatibility
type JointRPCServer interface {
	ListMethods(context.Context, *ListMethodsRequest) (*ListMethodsResponse, error)
	ListDelegates(context.Context, *ListDelegatesRequest) (*ListDelegatesResponse, error)
	DeclareMethods(context.Context, *DeclareMethodsRequest) (*DeclareMethodsResponse, error)
	Call(context.Context, *JSONRPCCallRequest) (*JSONRPCCallResult, error)
	Notify(context.Context, *JSONRPCNotifyRequest) (*JSONRPCNotifyResponse, error)
	Handle(JointRPC_HandleServer) error
	// cluster aware RPCs
	DeclareDelegates(context.Context, *DeclareDelegatesRequest) (*DeclareDelegatesResponse, error)
	mustEmbedUnimplementedJointRPCServer()
}

// UnimplementedJointRPCServer must be embedded to have forward compatible implementations.
type UnimplementedJointRPCServer struct {
}

func (UnimplementedJointRPCServer) ListMethods(context.Context, *ListMethodsRequest) (*ListMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMethods not implemented")
}
func (UnimplementedJointRPCServer) ListDelegates(context.Context, *ListDelegatesRequest) (*ListDelegatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDelegates not implemented")
}
func (UnimplementedJointRPCServer) DeclareMethods(context.Context, *DeclareMethodsRequest) (*DeclareMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclareMethods not implemented")
}
func (UnimplementedJointRPCServer) Call(context.Context, *JSONRPCCallRequest) (*JSONRPCCallResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedJointRPCServer) Notify(context.Context, *JSONRPCNotifyRequest) (*JSONRPCNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedJointRPCServer) Handle(JointRPC_HandleServer) error {
	return status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedJointRPCServer) DeclareDelegates(context.Context, *DeclareDelegatesRequest) (*DeclareDelegatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclareDelegates not implemented")
}
func (UnimplementedJointRPCServer) mustEmbedUnimplementedJointRPCServer() {}

// UnsafeJointRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JointRPCServer will
// result in compilation errors.
type UnsafeJointRPCServer interface {
	mustEmbedUnimplementedJointRPCServer()
}

func RegisterJointRPCServer(s *grpc.Server, srv JointRPCServer) {
	s.RegisterService(&_JointRPC_serviceDesc, srv)
}

func _JointRPC_ListMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointRPCServer).ListMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JointRPC/ListMethods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointRPCServer).ListMethods(ctx, req.(*ListMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointRPC_ListDelegates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDelegatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointRPCServer).ListDelegates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JointRPC/ListDelegates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointRPCServer).ListDelegates(ctx, req.(*ListDelegatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointRPC_DeclareMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclareMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointRPCServer).DeclareMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JointRPC/DeclareMethods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointRPCServer).DeclareMethods(ctx, req.(*DeclareMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointRPC_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JSONRPCCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointRPCServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JointRPC/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointRPCServer).Call(ctx, req.(*JSONRPCCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointRPC_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JSONRPCNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointRPCServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JointRPC/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointRPCServer).Notify(ctx, req.(*JSONRPCNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JointRPC_Handle_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JointRPCServer).Handle(&jointRPCHandleServer{stream})
}

type JointRPC_HandleServer interface {
	Send(*JointRPCDownPacket) error
	Recv() (*JointRPCUpPacket, error)
	grpc.ServerStream
}

type jointRPCHandleServer struct {
	grpc.ServerStream
}

func (x *jointRPCHandleServer) Send(m *JointRPCDownPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *jointRPCHandleServer) Recv() (*JointRPCUpPacket, error) {
	m := new(JointRPCUpPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _JointRPC_DeclareDelegates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclareDelegatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JointRPCServer).DeclareDelegates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JointRPC/DeclareDelegates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JointRPCServer).DeclareDelegates(ctx, req.(*DeclareDelegatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JointRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "JointRPC",
	HandlerType: (*JointRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMethods",
			Handler:    _JointRPC_ListMethods_Handler,
		},
		{
			MethodName: "ListDelegates",
			Handler:    _JointRPC_ListDelegates_Handler,
		},
		{
			MethodName: "DeclareMethods",
			Handler:    _JointRPC_DeclareMethods_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _JointRPC_Call_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _JointRPC_Notify_Handler,
		},
		{
			MethodName: "DeclareDelegates",
			Handler:    _JointRPC_DeclareDelegates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Handle",
			Handler:       _JointRPC_Handle_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "jointrpc.proto",
}
