// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: jointrpc.proto

package jointrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ClientAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ClientAuth) Reset() {
	*x = ClientAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuth) ProtoMessage() {}

func (x *ClientAuth) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuth.ProtoReflect.Descriptor instead.
func (*ClientAuth) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{2}
}

func (x *ClientAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JSONRPCEnvolope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body    string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"` // json encoded rpc message
	TraceId string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
}

func (x *JSONRPCEnvolope) Reset() {
	*x = JSONRPCEnvolope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCEnvolope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCEnvolope) ProtoMessage() {}

func (x *JSONRPCEnvolope) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCEnvolope.ProtoReflect.Descriptor instead.
func (*JSONRPCEnvolope) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{3}
}

func (x *JSONRPCEnvolope) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *JSONRPCEnvolope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ListMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth *ClientAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *ListMethodsRequest) Reset() {
	*x = ListMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsRequest) ProtoMessage() {}

func (x *ListMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListMethodsRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{4}
}

func (x *ListMethodsRequest) GetAuth() *ClientAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type ListMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Methods []*MethodInfo `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *ListMethodsResponse) Reset() {
	*x = ListMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsResponse) ProtoMessage() {}

func (x *ListMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListMethodsResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListMethodsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListMethodsResponse) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ListDelegatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth *ClientAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *ListDelegatesRequest) Reset() {
	*x = ListDelegatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDelegatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDelegatesRequest) ProtoMessage() {}

func (x *ListDelegatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDelegatesRequest.ProtoReflect.Descriptor instead.
func (*ListDelegatesRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{6}
}

func (x *ListDelegatesRequest) GetAuth() *ClientAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type ListDelegatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Delegates []string `protobuf:"bytes,2,rep,name=delegates,proto3" json:"delegates,omitempty"`
}

func (x *ListDelegatesResponse) Reset() {
	*x = ListDelegatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDelegatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDelegatesResponse) ProtoMessage() {}

func (x *ListDelegatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDelegatesResponse.ProtoReflect.Descriptor instead.
func (*ListDelegatesResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{7}
}

func (x *ListDelegatesResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListDelegatesResponse) GetDelegates() []string {
	if x != nil {
		return x.Delegates
	}
	return nil
}

type DeclareMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string        `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Methods   []*MethodInfo `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *DeclareMethodsRequest) Reset() {
	*x = DeclareMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclareMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareMethodsRequest) ProtoMessage() {}

func (x *DeclareMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareMethodsRequest.ProtoReflect.Descriptor instead.
func (*DeclareMethodsRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{8}
}

func (x *DeclareMethodsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeclareMethodsRequest) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type DeclareMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status    *Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeclareMethodsResponse) Reset() {
	*x = DeclareMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclareMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareMethodsResponse) ProtoMessage() {}

func (x *DeclareMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareMethodsResponse.ProtoReflect.Descriptor instead.
func (*DeclareMethodsResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{9}
}

func (x *DeclareMethodsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeclareMethodsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeclareDelegatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Methods   []string `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *DeclareDelegatesRequest) Reset() {
	*x = DeclareDelegatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclareDelegatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareDelegatesRequest) ProtoMessage() {}

func (x *DeclareDelegatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareDelegatesRequest.ProtoReflect.Descriptor instead.
func (*DeclareDelegatesRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{10}
}

func (x *DeclareDelegatesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeclareDelegatesRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type DeclareDelegatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status    *Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeclareDelegatesResponse) Reset() {
	*x = DeclareDelegatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclareDelegatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareDelegatesResponse) ProtoMessage() {}

func (x *DeclareDelegatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareDelegatesResponse.ProtoReflect.Descriptor instead.
func (*DeclareDelegatesResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{11}
}

func (x *DeclareDelegatesResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeclareDelegatesResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type JSONRPCCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth      *ClientAuth      `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Envolope  *JSONRPCEnvolope `protobuf:"bytes,2,opt,name=envolope,proto3" json:"envolope,omitempty"`
	Broadcast bool             `protobuf:"varint,3,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Timeout   int32            `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // the seconds from expire this rpc
}

func (x *JSONRPCCallRequest) Reset() {
	*x = JSONRPCCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCCallRequest) ProtoMessage() {}

func (x *JSONRPCCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCCallRequest.ProtoReflect.Descriptor instead.
func (*JSONRPCCallRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{12}
}

func (x *JSONRPCCallRequest) GetAuth() *ClientAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *JSONRPCCallRequest) GetEnvolope() *JSONRPCEnvolope {
	if x != nil {
		return x.Envolope
	}
	return nil
}

func (x *JSONRPCCallRequest) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

func (x *JSONRPCCallRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type JSONRPCCallResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *Status          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Envolope *JSONRPCEnvolope `protobuf:"bytes,2,opt,name=envolope,proto3" json:"envolope,omitempty"`
}

func (x *JSONRPCCallResult) Reset() {
	*x = JSONRPCCallResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCCallResult) ProtoMessage() {}

func (x *JSONRPCCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCCallResult.ProtoReflect.Descriptor instead.
func (*JSONRPCCallResult) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{13}
}

func (x *JSONRPCCallResult) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *JSONRPCCallResult) GetEnvolope() *JSONRPCEnvolope {
	if x != nil {
		return x.Envolope
	}
	return nil
}

type JSONRPCNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth      *ClientAuth      `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Envolope  *JSONRPCEnvolope `protobuf:"bytes,2,opt,name=envolope,proto3" json:"envolope,omitempty"`
	Broadcast bool             `protobuf:"varint,3,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
}

func (x *JSONRPCNotifyRequest) Reset() {
	*x = JSONRPCNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCNotifyRequest) ProtoMessage() {}

func (x *JSONRPCNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCNotifyRequest.ProtoReflect.Descriptor instead.
func (*JSONRPCNotifyRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{14}
}

func (x *JSONRPCNotifyRequest) GetAuth() *ClientAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *JSONRPCNotifyRequest) GetEnvolope() *JSONRPCEnvolope {
	if x != nil {
		return x.Envolope
	}
	return nil
}

func (x *JSONRPCNotifyRequest) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

type JSONRPCNotifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Text   string  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *JSONRPCNotifyResponse) Reset() {
	*x = JSONRPCNotifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCNotifyResponse) ProtoMessage() {}

func (x *JSONRPCNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCNotifyResponse.ProtoReflect.Descriptor instead.
func (*JSONRPCNotifyResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{15}
}

func (x *JSONRPCNotifyResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *JSONRPCNotifyResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MethodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//MethodLocation location = 2;
	Help       string `protobuf:"bytes,2,opt,name=help,proto3" json:"help,omitempty"`
	SchemaJson string `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
}

func (x *MethodInfo) Reset() {
	*x = MethodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodInfo) ProtoMessage() {}

func (x *MethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodInfo.ProtoReflect.Descriptor instead.
func (*MethodInfo) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{16}
}

func (x *MethodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodInfo) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *MethodInfo) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{17}
}

func (x *Ping) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{18}
}

func (x *Pong) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ServerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []*MethodInfo `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{19}
}

func (x *ServerState) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId  string      `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientAuth *ClientAuth `protobuf:"bytes,2,opt,name=client_auth,json=clientAuth,proto3" json:"client_auth,omitempty"`
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{20}
}

func (x *AuthRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthRequest) GetClientAuth() *ClientAuth {
	if x != nil {
		return x.ClientAuth
	}
	return nil
}

type AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RequestId string  `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{21}
}

func (x *AuthResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AuthResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type JointRPCDownPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JointRPCDownPacket_AuthResponse
	//	*JointRPCDownPacket_Ping
	//	*JointRPCDownPacket_Pong
	//	*JointRPCDownPacket_MethodsResponse
	//	*JointRPCDownPacket_DelegatesResponse
	//	*JointRPCDownPacket_Envolope
	//	*JointRPCDownPacket_State
	Payload isJointRPCDownPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JointRPCDownPacket) Reset() {
	*x = JointRPCDownPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JointRPCDownPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointRPCDownPacket) ProtoMessage() {}

func (x *JointRPCDownPacket) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointRPCDownPacket.ProtoReflect.Descriptor instead.
func (*JointRPCDownPacket) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{22}
}

func (m *JointRPCDownPacket) GetPayload() isJointRPCDownPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JointRPCDownPacket) GetAuthResponse() *AuthResponse {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_AuthResponse); ok {
		return x.AuthResponse
	}
	return nil
}

func (x *JointRPCDownPacket) GetPing() *Ping {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *JointRPCDownPacket) GetPong() *Pong {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *JointRPCDownPacket) GetMethodsResponse() *DeclareMethodsResponse {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_MethodsResponse); ok {
		return x.MethodsResponse
	}
	return nil
}

func (x *JointRPCDownPacket) GetDelegatesResponse() *DeclareDelegatesResponse {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_DelegatesResponse); ok {
		return x.DelegatesResponse
	}
	return nil
}

func (x *JointRPCDownPacket) GetEnvolope() *JSONRPCEnvolope {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_Envolope); ok {
		return x.Envolope
	}
	return nil
}

func (x *JointRPCDownPacket) GetState() *ServerState {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_State); ok {
		return x.State
	}
	return nil
}

type isJointRPCDownPacket_Payload interface {
	isJointRPCDownPacket_Payload()
}

type JointRPCDownPacket_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,1,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type JointRPCDownPacket_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type JointRPCDownPacket_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

type JointRPCDownPacket_MethodsResponse struct {
	MethodsResponse *DeclareMethodsResponse `protobuf:"bytes,4,opt,name=methods_response,json=methodsResponse,proto3,oneof"`
}

type JointRPCDownPacket_DelegatesResponse struct {
	DelegatesResponse *DeclareDelegatesResponse `protobuf:"bytes,5,opt,name=delegates_response,json=delegatesResponse,proto3,oneof"`
}

type JointRPCDownPacket_Envolope struct {
	Envolope *JSONRPCEnvolope `protobuf:"bytes,10,opt,name=envolope,proto3,oneof"`
}

type JointRPCDownPacket_State struct {
	State *ServerState `protobuf:"bytes,11,opt,name=state,proto3,oneof"` // server state notification
}

func (*JointRPCDownPacket_AuthResponse) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_Ping) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_Pong) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_MethodsResponse) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_DelegatesResponse) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_Envolope) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_State) isJointRPCDownPacket_Payload() {}

type JointRPCUpPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JointRPCUpPacket_AuthRequest
	//	*JointRPCUpPacket_Ping
	//	*JointRPCUpPacket_Pong
	//	*JointRPCUpPacket_MethodsRequest
	//	*JointRPCUpPacket_DelegatesRequest
	//	*JointRPCUpPacket_Envolope
	Payload isJointRPCUpPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JointRPCUpPacket) Reset() {
	*x = JointRPCUpPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JointRPCUpPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointRPCUpPacket) ProtoMessage() {}

func (x *JointRPCUpPacket) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointRPCUpPacket.ProtoReflect.Descriptor instead.
func (*JointRPCUpPacket) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{23}
}

func (m *JointRPCUpPacket) GetPayload() isJointRPCUpPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JointRPCUpPacket) GetAuthRequest() *AuthRequest {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_AuthRequest); ok {
		return x.AuthRequest
	}
	return nil
}

func (x *JointRPCUpPacket) GetPing() *Ping {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *JointRPCUpPacket) GetPong() *Pong {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *JointRPCUpPacket) GetMethodsRequest() *DeclareMethodsRequest {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_MethodsRequest); ok {
		return x.MethodsRequest
	}
	return nil
}

func (x *JointRPCUpPacket) GetDelegatesRequest() *DeclareDelegatesRequest {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_DelegatesRequest); ok {
		return x.DelegatesRequest
	}
	return nil
}

func (x *JointRPCUpPacket) GetEnvolope() *JSONRPCEnvolope {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_Envolope); ok {
		return x.Envolope
	}
	return nil
}

type isJointRPCUpPacket_Payload interface {
	isJointRPCUpPacket_Payload()
}

type JointRPCUpPacket_AuthRequest struct {
	AuthRequest *AuthRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type JointRPCUpPacket_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type JointRPCUpPacket_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

type JointRPCUpPacket_MethodsRequest struct {
	MethodsRequest *DeclareMethodsRequest `protobuf:"bytes,4,opt,name=methods_request,json=methodsRequest,proto3,oneof"`
}

type JointRPCUpPacket_DelegatesRequest struct {
	DelegatesRequest *DeclareDelegatesRequest `protobuf:"bytes,5,opt,name=delegates_request,json=delegatesRequest,proto3,oneof"`
}

type JointRPCUpPacket_Envolope struct {
	Envolope *JSONRPCEnvolope `protobuf:"bytes,10,opt,name=envolope,proto3,oneof"`
}

func (*JointRPCUpPacket_AuthRequest) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_Ping) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_Pong) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_MethodsRequest) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_DelegatesRequest) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_Envolope) isJointRPCUpPacket_Payload() {}

type SubscribeStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*SubscribeStateResponse_AuthResponse
	//	*SubscribeStateResponse_State
	Payload isSubscribeStateResponse_Payload `protobuf_oneof:"payload"`
}

func (x *SubscribeStateResponse) Reset() {
	*x = SubscribeStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeStateResponse) ProtoMessage() {}

func (x *SubscribeStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeStateResponse.ProtoReflect.Descriptor instead.
func (*SubscribeStateResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{24}
}

func (m *SubscribeStateResponse) GetPayload() isSubscribeStateResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SubscribeStateResponse) GetAuthResponse() *AuthResponse {
	if x, ok := x.GetPayload().(*SubscribeStateResponse_AuthResponse); ok {
		return x.AuthResponse
	}
	return nil
}

func (x *SubscribeStateResponse) GetState() *ServerState {
	if x, ok := x.GetPayload().(*SubscribeStateResponse_State); ok {
		return x.State
	}
	return nil
}

type isSubscribeStateResponse_Payload interface {
	isSubscribeStateResponse_Payload()
}

type SubscribeStateResponse_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,1,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type SubscribeStateResponse_State struct {
	State *ServerState `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

func (*SubscribeStateResponse_AuthResponse) isSubscribeStateResponse_Payload() {}

func (*SubscribeStateResponse_State) isSubscribeStateResponse_Payload() {}

var File_jointrpc_proto protoreflect.FileDescriptor

var file_jointrpc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6a, 0x6f, 0x69, 0x6e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x44, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x40, 0x0a, 0x0f, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43,
	0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x5d,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x37, 0x0a,
	0x14, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x56, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x22, 0x5d,
	0x0a, 0x15, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x58, 0x0a,
	0x16, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x52, 0x0a, 0x17, 0x44, 0x65, 0x63, 0x6c, 0x61,
	0x72, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x5a, 0x0a, 0x18, 0x44,
	0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x12, 0x4a, 0x53, 0x4f, 0x4e,
	0x52, 0x50, 0x43, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12,
	0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x76, 0x6f, 0x6c,
	0x6f, 0x70, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x62, 0x0a, 0x11, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x65,
	0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x52,
	0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x14, 0x4a, 0x53,
	0x4f, 0x4e, 0x52, 0x50, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61,
	0x75, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x45,
	0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x22,
	0x4c, 0x0a, 0x15, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x55, 0x0a,
	0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x65, 0x6c, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x6a, 0x73,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x04, 0x50,
	0x6f, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x34, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x25, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x5a, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x41, 0x75, 0x74, 0x68, 0x22, 0x4e, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x22, 0xf7, 0x02, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x50,
	0x43, 0x44, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x34, 0x0a, 0x0d, 0x61,
	0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1b,
	0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50,
	0x6f, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x44, 0x0a, 0x10, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x0f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x12, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x64, 0x65, 0x6c, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70,
	0x65, 0x48, 0x00, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x24, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xc6,
	0x02, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x50, 0x43, 0x55, 0x70, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x31, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70,
	0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x12, 0x41, 0x0a, 0x0f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x44, 0x65, 0x63, 0x6c,
	0x61, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x11, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x10, 0x64, 0x65, 0x6c, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08,
	0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x7f, 0x0a, 0x16, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x34, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0xdf, 0x02, 0x0a, 0x08, 0x4a, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x50, 0x43, 0x12, 0x2f, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x13, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x43, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x15, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50,
	0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x13,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x12, 0x34, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x11,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x50, 0x43, 0x55, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x1a, 0x13, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x50, 0x43, 0x44, 0x6f, 0x77, 0x6e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x69, 0x6e,
	0x74, 0x66, 0x2f, 0x6a, 0x6f, 0x69, 0x6e, 0x74, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_jointrpc_proto_rawDescOnce sync.Once
	file_jointrpc_proto_rawDescData = file_jointrpc_proto_rawDesc
)

func file_jointrpc_proto_rawDescGZIP() []byte {
	file_jointrpc_proto_rawDescOnce.Do(func() {
		file_jointrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_jointrpc_proto_rawDescData)
	})
	return file_jointrpc_proto_rawDescData
}

var file_jointrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_jointrpc_proto_goTypes = []interface{}{
	(*Empty)(nil),                    // 0: Empty
	(*Status)(nil),                   // 1: Status
	(*ClientAuth)(nil),               // 2: ClientAuth
	(*JSONRPCEnvolope)(nil),          // 3: JSONRPCEnvolope
	(*ListMethodsRequest)(nil),       // 4: ListMethodsRequest
	(*ListMethodsResponse)(nil),      // 5: ListMethodsResponse
	(*ListDelegatesRequest)(nil),     // 6: ListDelegatesRequest
	(*ListDelegatesResponse)(nil),    // 7: ListDelegatesResponse
	(*DeclareMethodsRequest)(nil),    // 8: DeclareMethodsRequest
	(*DeclareMethodsResponse)(nil),   // 9: DeclareMethodsResponse
	(*DeclareDelegatesRequest)(nil),  // 10: DeclareDelegatesRequest
	(*DeclareDelegatesResponse)(nil), // 11: DeclareDelegatesResponse
	(*JSONRPCCallRequest)(nil),       // 12: JSONRPCCallRequest
	(*JSONRPCCallResult)(nil),        // 13: JSONRPCCallResult
	(*JSONRPCNotifyRequest)(nil),     // 14: JSONRPCNotifyRequest
	(*JSONRPCNotifyResponse)(nil),    // 15: JSONRPCNotifyResponse
	(*MethodInfo)(nil),               // 16: MethodInfo
	(*Ping)(nil),                     // 17: Ping
	(*Pong)(nil),                     // 18: Pong
	(*ServerState)(nil),              // 19: ServerState
	(*AuthRequest)(nil),              // 20: AuthRequest
	(*AuthResponse)(nil),             // 21: AuthResponse
	(*JointRPCDownPacket)(nil),       // 22: JointRPCDownPacket
	(*JointRPCUpPacket)(nil),         // 23: JointRPCUpPacket
	(*SubscribeStateResponse)(nil),   // 24: SubscribeStateResponse
}
var file_jointrpc_proto_depIdxs = []int32{
	2,  // 0: ListMethodsRequest.auth:type_name -> ClientAuth
	1,  // 1: ListMethodsResponse.status:type_name -> Status
	16, // 2: ListMethodsResponse.methods:type_name -> MethodInfo
	2,  // 3: ListDelegatesRequest.auth:type_name -> ClientAuth
	1,  // 4: ListDelegatesResponse.status:type_name -> Status
	16, // 5: DeclareMethodsRequest.methods:type_name -> MethodInfo
	1,  // 6: DeclareMethodsResponse.status:type_name -> Status
	1,  // 7: DeclareDelegatesResponse.status:type_name -> Status
	2,  // 8: JSONRPCCallRequest.auth:type_name -> ClientAuth
	3,  // 9: JSONRPCCallRequest.envolope:type_name -> JSONRPCEnvolope
	1,  // 10: JSONRPCCallResult.status:type_name -> Status
	3,  // 11: JSONRPCCallResult.envolope:type_name -> JSONRPCEnvolope
	2,  // 12: JSONRPCNotifyRequest.auth:type_name -> ClientAuth
	3,  // 13: JSONRPCNotifyRequest.envolope:type_name -> JSONRPCEnvolope
	1,  // 14: JSONRPCNotifyResponse.status:type_name -> Status
	16, // 15: ServerState.methods:type_name -> MethodInfo
	2,  // 16: AuthRequest.client_auth:type_name -> ClientAuth
	1,  // 17: AuthResponse.status:type_name -> Status
	21, // 18: JointRPCDownPacket.auth_response:type_name -> AuthResponse
	17, // 19: JointRPCDownPacket.ping:type_name -> Ping
	18, // 20: JointRPCDownPacket.pong:type_name -> Pong
	9,  // 21: JointRPCDownPacket.methods_response:type_name -> DeclareMethodsResponse
	11, // 22: JointRPCDownPacket.delegates_response:type_name -> DeclareDelegatesResponse
	3,  // 23: JointRPCDownPacket.envolope:type_name -> JSONRPCEnvolope
	19, // 24: JointRPCDownPacket.state:type_name -> ServerState
	20, // 25: JointRPCUpPacket.auth_request:type_name -> AuthRequest
	17, // 26: JointRPCUpPacket.ping:type_name -> Ping
	18, // 27: JointRPCUpPacket.pong:type_name -> Pong
	8,  // 28: JointRPCUpPacket.methods_request:type_name -> DeclareMethodsRequest
	10, // 29: JointRPCUpPacket.delegates_request:type_name -> DeclareDelegatesRequest
	3,  // 30: JointRPCUpPacket.envolope:type_name -> JSONRPCEnvolope
	21, // 31: SubscribeStateResponse.auth_response:type_name -> AuthResponse
	19, // 32: SubscribeStateResponse.state:type_name -> ServerState
	12, // 33: JointRPC.Call:input_type -> JSONRPCCallRequest
	14, // 34: JointRPC.Notify:input_type -> JSONRPCNotifyRequest
	4,  // 35: JointRPC.ListMethods:input_type -> ListMethodsRequest
	6,  // 36: JointRPC.ListDelegates:input_type -> ListDelegatesRequest
	20, // 37: JointRPC.SubscribeState:input_type -> AuthRequest
	23, // 38: JointRPC.Worker:input_type -> JointRPCUpPacket
	13, // 39: JointRPC.Call:output_type -> JSONRPCCallResult
	15, // 40: JointRPC.Notify:output_type -> JSONRPCNotifyResponse
	5,  // 41: JointRPC.ListMethods:output_type -> ListMethodsResponse
	7,  // 42: JointRPC.ListDelegates:output_type -> ListDelegatesResponse
	24, // 43: JointRPC.SubscribeState:output_type -> SubscribeStateResponse
	22, // 44: JointRPC.Worker:output_type -> JointRPCDownPacket
	39, // [39:45] is the sub-list for method output_type
	33, // [33:39] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_jointrpc_proto_init() }
func file_jointrpc_proto_init() {
	if File_jointrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jointrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCEnvolope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDelegatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDelegatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclareMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclareMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclareDelegatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclareDelegatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCCallResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCNotifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JointRPCDownPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JointRPCUpPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_jointrpc_proto_msgTypes[22].OneofWrappers = []interface{}{
		(*JointRPCDownPacket_AuthResponse)(nil),
		(*JointRPCDownPacket_Ping)(nil),
		(*JointRPCDownPacket_Pong)(nil),
		(*JointRPCDownPacket_MethodsResponse)(nil),
		(*JointRPCDownPacket_DelegatesResponse)(nil),
		(*JointRPCDownPacket_Envolope)(nil),
		(*JointRPCDownPacket_State)(nil),
	}
	file_jointrpc_proto_msgTypes[23].OneofWrappers = []interface{}{
		(*JointRPCUpPacket_AuthRequest)(nil),
		(*JointRPCUpPacket_Ping)(nil),
		(*JointRPCUpPacket_Pong)(nil),
		(*JointRPCUpPacket_MethodsRequest)(nil),
		(*JointRPCUpPacket_DelegatesRequest)(nil),
		(*JointRPCUpPacket_Envolope)(nil),
	}
	file_jointrpc_proto_msgTypes[24].OneofWrappers = []interface{}{
		(*SubscribeStateResponse_AuthResponse)(nil),
		(*SubscribeStateResponse_State)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jointrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jointrpc_proto_goTypes,
		DependencyIndexes: file_jointrpc_proto_depIdxs,
		MessageInfos:      file_jointrpc_proto_msgTypes,
	}.Build()
	File_jointrpc_proto = out.File
	file_jointrpc_proto_rawDesc = nil
	file_jointrpc_proto_goTypes = nil
	file_jointrpc_proto_depIdxs = nil
}
