// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: jointrpc.proto

package jointrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{0}
}

type ListMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMethodsRequest) Reset() {
	*x = ListMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsRequest) ProtoMessage() {}

func (x *ListMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListMethodsRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{1}
}

type ListMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodInfos []*MethodInfo `protobuf:"bytes,1,rep,name=method_infos,json=methodInfos,proto3" json:"method_infos,omitempty"`
}

func (x *ListMethodsResponse) Reset() {
	*x = ListMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsResponse) ProtoMessage() {}

func (x *ListMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListMethodsResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{2}
}

func (x *ListMethodsResponse) GetMethodInfos() []*MethodInfo {
	if x != nil {
		return x.MethodInfos
	}
	return nil
}

type ListDelegatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDelegatesRequest) Reset() {
	*x = ListDelegatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDelegatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDelegatesRequest) ProtoMessage() {}

func (x *ListDelegatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDelegatesRequest.ProtoReflect.Descriptor instead.
func (*ListDelegatesRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{3}
}

type ListDelegatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delegates []string `protobuf:"bytes,1,rep,name=delegates,proto3" json:"delegates,omitempty"`
}

func (x *ListDelegatesResponse) Reset() {
	*x = ListDelegatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDelegatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDelegatesResponse) ProtoMessage() {}

func (x *ListDelegatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDelegatesResponse.ProtoReflect.Descriptor instead.
func (*ListDelegatesResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{4}
}

func (x *ListDelegatesResponse) GetDelegates() []string {
	if x != nil {
		return x.Delegates
	}
	return nil
}

type JSONRPCEnvolope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"` // json encoded rpc message
}

func (x *JSONRPCEnvolope) Reset() {
	*x = JSONRPCEnvolope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCEnvolope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCEnvolope) ProtoMessage() {}

func (x *JSONRPCEnvolope) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCEnvolope.ProtoReflect.Descriptor instead.
func (*JSONRPCEnvolope) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{5}
}

func (x *JSONRPCEnvolope) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type JSONRPCCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envolope *JSONRPCEnvolope `protobuf:"bytes,1,opt,name=envolope,proto3" json:"envolope,omitempty"`
}

func (x *JSONRPCCallRequest) Reset() {
	*x = JSONRPCCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCCallRequest) ProtoMessage() {}

func (x *JSONRPCCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCCallRequest.ProtoReflect.Descriptor instead.
func (*JSONRPCCallRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{6}
}

func (x *JSONRPCCallRequest) GetEnvolope() *JSONRPCEnvolope {
	if x != nil {
		return x.Envolope
	}
	return nil
}

type JSONRPCCallResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envolope *JSONRPCEnvolope `protobuf:"bytes,1,opt,name=envolope,proto3" json:"envolope,omitempty"`
}

func (x *JSONRPCCallResult) Reset() {
	*x = JSONRPCCallResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCCallResult) ProtoMessage() {}

func (x *JSONRPCCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCCallResult.ProtoReflect.Descriptor instead.
func (*JSONRPCCallResult) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{7}
}

func (x *JSONRPCCallResult) GetEnvolope() *JSONRPCEnvolope {
	if x != nil {
		return x.Envolope
	}
	return nil
}

type JSONRPCNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envolope  *JSONRPCEnvolope `protobuf:"bytes,1,opt,name=envolope,proto3" json:"envolope,omitempty"`
	Broadcast bool             `protobuf:"varint,2,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
}

func (x *JSONRPCNotifyRequest) Reset() {
	*x = JSONRPCNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCNotifyRequest) ProtoMessage() {}

func (x *JSONRPCNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCNotifyRequest.ProtoReflect.Descriptor instead.
func (*JSONRPCNotifyRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{8}
}

func (x *JSONRPCNotifyRequest) GetEnvolope() *JSONRPCEnvolope {
	if x != nil {
		return x.Envolope
	}
	return nil
}

func (x *JSONRPCNotifyRequest) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

type JSONRPCNotifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *JSONRPCNotifyResponse) Reset() {
	*x = JSONRPCNotifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONRPCNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCNotifyResponse) ProtoMessage() {}

func (x *JSONRPCNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCNotifyResponse.ProtoReflect.Descriptor instead.
func (*JSONRPCNotifyResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{9}
}

func (x *JSONRPCNotifyResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MethodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//MethodLocation location = 2;
	Help       string `protobuf:"bytes,2,opt,name=help,proto3" json:"help,omitempty"`
	SchemaJson string `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
}

func (x *MethodInfo) Reset() {
	*x = MethodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodInfo) ProtoMessage() {}

func (x *MethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodInfo.ProtoReflect.Descriptor instead.
func (*MethodInfo) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{10}
}

func (x *MethodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodInfo) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *MethodInfo) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type CanServeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []*MethodInfo `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *CanServeRequest) Reset() {
	*x = CanServeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanServeRequest) ProtoMessage() {}

func (x *CanServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanServeRequest.ProtoReflect.Descriptor instead.
func (*CanServeRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{11}
}

func (x *CanServeRequest) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type CanServeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CanServeResponse) Reset() {
	*x = CanServeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanServeResponse) ProtoMessage() {}

func (x *CanServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanServeResponse.ProtoReflect.Descriptor instead.
func (*CanServeResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{12}
}

func (x *CanServeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CanDelegateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *CanDelegateRequest) Reset() {
	*x = CanDelegateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanDelegateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanDelegateRequest) ProtoMessage() {}

func (x *CanDelegateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanDelegateRequest.ProtoReflect.Descriptor instead.
func (*CanDelegateRequest) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{13}
}

func (x *CanDelegateRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type CanDelegateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CanDelegateResponse) Reset() {
	*x = CanDelegateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanDelegateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanDelegateResponse) ProtoMessage() {}

func (x *CanDelegateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanDelegateResponse.ProtoReflect.Descriptor instead.
func (*CanDelegateResponse) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{14}
}

func (x *CanDelegateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PING struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PING) Reset() {
	*x = PING{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PING) ProtoMessage() {}

func (x *PING) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PING.ProtoReflect.Descriptor instead.
func (*PING) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{15}
}

func (x *PING) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PONG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PONG) Reset() {
	*x = PONG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PONG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PONG) ProtoMessage() {}

func (x *PONG) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PONG.ProtoReflect.Descriptor instead.
func (*PONG) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{16}
}

func (x *PONG) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TubeState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []*MethodInfo `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *TubeState) Reset() {
	*x = TubeState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TubeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TubeState) ProtoMessage() {}

func (x *TubeState) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TubeState.ProtoReflect.Descriptor instead.
func (*TubeState) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{17}
}

func (x *TubeState) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type JointRPCDownPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JointRPCDownPacket_CanServe
	//	*JointRPCDownPacket_CanDelegate
	//	*JointRPCDownPacket_Ping
	//	*JointRPCDownPacket_Pong
	//	*JointRPCDownPacket_State
	//	*JointRPCDownPacket_Envolope
	Payload isJointRPCDownPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JointRPCDownPacket) Reset() {
	*x = JointRPCDownPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JointRPCDownPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointRPCDownPacket) ProtoMessage() {}

func (x *JointRPCDownPacket) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointRPCDownPacket.ProtoReflect.Descriptor instead.
func (*JointRPCDownPacket) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{18}
}

func (m *JointRPCDownPacket) GetPayload() isJointRPCDownPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JointRPCDownPacket) GetCanServe() *CanServeResponse {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_CanServe); ok {
		return x.CanServe
	}
	return nil
}

func (x *JointRPCDownPacket) GetCanDelegate() *CanDelegateResponse {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_CanDelegate); ok {
		return x.CanDelegate
	}
	return nil
}

func (x *JointRPCDownPacket) GetPing() *PING {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *JointRPCDownPacket) GetPong() *PONG {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *JointRPCDownPacket) GetState() *TubeState {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_State); ok {
		return x.State
	}
	return nil
}

func (x *JointRPCDownPacket) GetEnvolope() *JSONRPCEnvolope {
	if x, ok := x.GetPayload().(*JointRPCDownPacket_Envolope); ok {
		return x.Envolope
	}
	return nil
}

type isJointRPCDownPacket_Payload interface {
	isJointRPCDownPacket_Payload()
}

type JointRPCDownPacket_CanServe struct {
	CanServe *CanServeResponse `protobuf:"bytes,1,opt,name=can_serve,json=canServe,proto3,oneof"`
}

type JointRPCDownPacket_CanDelegate struct {
	CanDelegate *CanDelegateResponse `protobuf:"bytes,2,opt,name=can_delegate,json=canDelegate,proto3,oneof"`
}

type JointRPCDownPacket_Ping struct {
	Ping *PING `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type JointRPCDownPacket_Pong struct {
	Pong *PONG `protobuf:"bytes,11,opt,name=pong,proto3,oneof"`
}

type JointRPCDownPacket_State struct {
	State *TubeState `protobuf:"bytes,15,opt,name=state,proto3,oneof"`
}

type JointRPCDownPacket_Envolope struct {
	Envolope *JSONRPCEnvolope `protobuf:"bytes,20,opt,name=envolope,proto3,oneof"`
}

func (*JointRPCDownPacket_CanServe) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_CanDelegate) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_Ping) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_Pong) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_State) isJointRPCDownPacket_Payload() {}

func (*JointRPCDownPacket_Envolope) isJointRPCDownPacket_Payload() {}

type JointRPCUpPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*JointRPCUpPacket_CanServe
	//	*JointRPCUpPacket_CanDelegate
	//	*JointRPCUpPacket_Ping
	//	*JointRPCUpPacket_Pong
	//	*JointRPCUpPacket_Envolope
	Payload isJointRPCUpPacket_Payload `protobuf_oneof:"payload"`
}

func (x *JointRPCUpPacket) Reset() {
	*x = JointRPCUpPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jointrpc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JointRPCUpPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointRPCUpPacket) ProtoMessage() {}

func (x *JointRPCUpPacket) ProtoReflect() protoreflect.Message {
	mi := &file_jointrpc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointRPCUpPacket.ProtoReflect.Descriptor instead.
func (*JointRPCUpPacket) Descriptor() ([]byte, []int) {
	return file_jointrpc_proto_rawDescGZIP(), []int{19}
}

func (m *JointRPCUpPacket) GetPayload() isJointRPCUpPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *JointRPCUpPacket) GetCanServe() *CanServeRequest {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_CanServe); ok {
		return x.CanServe
	}
	return nil
}

func (x *JointRPCUpPacket) GetCanDelegate() *CanDelegateRequest {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_CanDelegate); ok {
		return x.CanDelegate
	}
	return nil
}

func (x *JointRPCUpPacket) GetPing() *PING {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *JointRPCUpPacket) GetPong() *PONG {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *JointRPCUpPacket) GetEnvolope() *JSONRPCEnvolope {
	if x, ok := x.GetPayload().(*JointRPCUpPacket_Envolope); ok {
		return x.Envolope
	}
	return nil
}

type isJointRPCUpPacket_Payload interface {
	isJointRPCUpPacket_Payload()
}

type JointRPCUpPacket_CanServe struct {
	CanServe *CanServeRequest `protobuf:"bytes,1,opt,name=can_serve,json=canServe,proto3,oneof"`
}

type JointRPCUpPacket_CanDelegate struct {
	CanDelegate *CanDelegateRequest `protobuf:"bytes,2,opt,name=can_delegate,json=canDelegate,proto3,oneof"`
}

type JointRPCUpPacket_Ping struct {
	Ping *PING `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type JointRPCUpPacket_Pong struct {
	Pong *PONG `protobuf:"bytes,11,opt,name=pong,proto3,oneof"`
}

type JointRPCUpPacket_Envolope struct {
	Envolope *JSONRPCEnvolope `protobuf:"bytes,20,opt,name=envolope,proto3,oneof"`
}

func (*JointRPCUpPacket_CanServe) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_CanDelegate) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_Ping) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_Pong) isJointRPCUpPacket_Payload() {}

func (*JointRPCUpPacket_Envolope) isJointRPCUpPacket_Payload() {}

var File_jointrpc_proto protoreflect.FileDescriptor

var file_jointrpc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6a, 0x6f, 0x69, 0x6e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x45, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43,
	0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x42, 0x0a, 0x12,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x45, 0x6e,
	0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65,
	0x22, 0x41, 0x0a, 0x11, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50,
	0x43, 0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c,
	0x6f, 0x70, 0x65, 0x22, 0x62, 0x0a, 0x14, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x65,
	0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x52,
	0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x15, 0x4a, 0x53, 0x4f, 0x4e, 0x52,
	0x50, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x55, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x38, 0x0a, 0x0f, 0x43,
	0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2e, 0x0a,
	0x12, 0x43, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x29, 0x0a,
	0x13, 0x43, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x32, 0x0a, 0x09, 0x54, 0x75, 0x62, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a,
	0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x22, 0x9a, 0x02, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x50,
	0x43, 0x44, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x63,
	0x61, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x43, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x08, 0x63, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x12, 0x39, 0x0a,
	0x0c, 0x63, 0x61, 0x6e, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x6e,
	0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x49, 0x4e, 0x47, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x4f, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f,
	0x6e, 0x67, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x75, 0x62, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f,
	0x70, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52,
	0x50, 0x43, 0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x48, 0x00, 0x52, 0x08, 0x65, 0x6e,
	0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0xf2, 0x01, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x50, 0x43, 0x55, 0x70,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x61, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x63,
	0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x5f, 0x64,
	0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x43, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x50, 0x49, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1b,
	0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50,
	0x4f, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x08, 0x65,
	0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x48,
	0x00, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x6f, 0x6c, 0x6f, 0x70, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0xa4, 0x02, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x50, 0x43, 0x12, 0x38, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x12, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x0d, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x12, 0x15,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a,
	0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x43,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4a, 0x53, 0x4f,
	0x4e, 0x52, 0x50, 0x43, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x37,
	0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x15, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52,
	0x50, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x50, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x12, 0x11, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x50, 0x43, 0x55, 0x70, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x1a, 0x13, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x50, 0x43, 0x44,
	0x6f, 0x77, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a,
	0x0d, 0x69, 0x6e, 0x74, 0x66, 0x2f, 0x6a, 0x6f, 0x69, 0x6e, 0x74, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jointrpc_proto_rawDescOnce sync.Once
	file_jointrpc_proto_rawDescData = file_jointrpc_proto_rawDesc
)

func file_jointrpc_proto_rawDescGZIP() []byte {
	file_jointrpc_proto_rawDescOnce.Do(func() {
		file_jointrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_jointrpc_proto_rawDescData)
	})
	return file_jointrpc_proto_rawDescData
}

var file_jointrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_jointrpc_proto_goTypes = []interface{}{
	(*Empty)(nil),                 // 0: Empty
	(*ListMethodsRequest)(nil),    // 1: ListMethodsRequest
	(*ListMethodsResponse)(nil),   // 2: ListMethodsResponse
	(*ListDelegatesRequest)(nil),  // 3: ListDelegatesRequest
	(*ListDelegatesResponse)(nil), // 4: ListDelegatesResponse
	(*JSONRPCEnvolope)(nil),       // 5: JSONRPCEnvolope
	(*JSONRPCCallRequest)(nil),    // 6: JSONRPCCallRequest
	(*JSONRPCCallResult)(nil),     // 7: JSONRPCCallResult
	(*JSONRPCNotifyRequest)(nil),  // 8: JSONRPCNotifyRequest
	(*JSONRPCNotifyResponse)(nil), // 9: JSONRPCNotifyResponse
	(*MethodInfo)(nil),            // 10: MethodInfo
	(*CanServeRequest)(nil),       // 11: CanServeRequest
	(*CanServeResponse)(nil),      // 12: CanServeResponse
	(*CanDelegateRequest)(nil),    // 13: CanDelegateRequest
	(*CanDelegateResponse)(nil),   // 14: CanDelegateResponse
	(*PING)(nil),                  // 15: PING
	(*PONG)(nil),                  // 16: PONG
	(*TubeState)(nil),             // 17: TubeState
	(*JointRPCDownPacket)(nil),    // 18: JointRPCDownPacket
	(*JointRPCUpPacket)(nil),      // 19: JointRPCUpPacket
}
var file_jointrpc_proto_depIdxs = []int32{
	10, // 0: ListMethodsResponse.method_infos:type_name -> MethodInfo
	5,  // 1: JSONRPCCallRequest.envolope:type_name -> JSONRPCEnvolope
	5,  // 2: JSONRPCCallResult.envolope:type_name -> JSONRPCEnvolope
	5,  // 3: JSONRPCNotifyRequest.envolope:type_name -> JSONRPCEnvolope
	10, // 4: CanServeRequest.methods:type_name -> MethodInfo
	10, // 5: TubeState.methods:type_name -> MethodInfo
	12, // 6: JointRPCDownPacket.can_serve:type_name -> CanServeResponse
	14, // 7: JointRPCDownPacket.can_delegate:type_name -> CanDelegateResponse
	15, // 8: JointRPCDownPacket.ping:type_name -> PING
	16, // 9: JointRPCDownPacket.pong:type_name -> PONG
	17, // 10: JointRPCDownPacket.state:type_name -> TubeState
	5,  // 11: JointRPCDownPacket.envolope:type_name -> JSONRPCEnvolope
	11, // 12: JointRPCUpPacket.can_serve:type_name -> CanServeRequest
	13, // 13: JointRPCUpPacket.can_delegate:type_name -> CanDelegateRequest
	15, // 14: JointRPCUpPacket.ping:type_name -> PING
	16, // 15: JointRPCUpPacket.pong:type_name -> PONG
	5,  // 16: JointRPCUpPacket.envolope:type_name -> JSONRPCEnvolope
	1,  // 17: JointRPC.ListMethods:input_type -> ListMethodsRequest
	3,  // 18: JointRPC.ListDelegates:input_type -> ListDelegatesRequest
	6,  // 19: JointRPC.Call:input_type -> JSONRPCCallRequest
	8,  // 20: JointRPC.Notify:input_type -> JSONRPCNotifyRequest
	19, // 21: JointRPC.Handle:input_type -> JointRPCUpPacket
	2,  // 22: JointRPC.ListMethods:output_type -> ListMethodsResponse
	4,  // 23: JointRPC.ListDelegates:output_type -> ListDelegatesResponse
	7,  // 24: JointRPC.Call:output_type -> JSONRPCCallResult
	9,  // 25: JointRPC.Notify:output_type -> JSONRPCNotifyResponse
	18, // 26: JointRPC.Handle:output_type -> JointRPCDownPacket
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_jointrpc_proto_init() }
func file_jointrpc_proto_init() {
	if File_jointrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jointrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDelegatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDelegatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCEnvolope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCCallResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONRPCNotifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanServeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanServeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanDelegateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanDelegateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PING); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PONG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TubeState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JointRPCDownPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jointrpc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JointRPCUpPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_jointrpc_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*JointRPCDownPacket_CanServe)(nil),
		(*JointRPCDownPacket_CanDelegate)(nil),
		(*JointRPCDownPacket_Ping)(nil),
		(*JointRPCDownPacket_Pong)(nil),
		(*JointRPCDownPacket_State)(nil),
		(*JointRPCDownPacket_Envolope)(nil),
	}
	file_jointrpc_proto_msgTypes[19].OneofWrappers = []interface{}{
		(*JointRPCUpPacket_CanServe)(nil),
		(*JointRPCUpPacket_CanDelegate)(nil),
		(*JointRPCUpPacket_Ping)(nil),
		(*JointRPCUpPacket_Pong)(nil),
		(*JointRPCUpPacket_Envolope)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jointrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jointrpc_proto_goTypes,
		DependencyIndexes: file_jointrpc_proto_depIdxs,
		MessageInfos:      file_jointrpc_proto_msgTypes,
	}.Build()
	File_jointrpc_proto = out.File
	file_jointrpc_proto_rawDesc = nil
	file_jointrpc_proto_goTypes = nil
	file_jointrpc_proto_depIdxs = nil
}
